package techbrain.wikibot.utils;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

public class WikiQuotes {

	Set<String> quotes = new HashSet<>(Arrays.asList(
		"Ancora un anno è bruciato, senza un lamento, senza un grido levato a vincere d\'improvviso un giorno. (Salvatore Quasimodo)",
		"Io mi dico: è stato meglio lasciarci che non esserci mai incontrati. (Fabrizio De André)",
		"Mi piace il lavoro, mi affascina. Potrei stare per ore seduto ad osservarlo... (Jerome Klapka Jerome)",
		"Il mondo è pieno di cose ovvie che nessuno si prende mai la cura di osservare. (Arthur Conan Doyle)",
		"Conoscete quale sia il vostro vero valore, e non vi perderete. (Khalil Gibran)",
		"Nessuno ha amore più grande di colui che sa rispettare la libertà dell\'altro. (attribuita a Simone Weil)",
		"Per evitare un difetto, gli stolti cadono nel difetto contrario. (Quinto Orazio Flacco)",
		"Dove c\'è molta luce, l\'ombra è più nera. (Johann Wolfgang von Goethe)",
		"L\'uomo è condannato ad essere libero. (Jean-Paul Sartre)",
		"Il cervello è come lo stomaco: quello che conta non è quanto ci metti dentro, ma quanto riesce a digerire. (Albert Jay Nock)",
		"L\'uomo non è fatto per la sconfitta. Un uomo può essere distrutto, ma non può essere sconfitto. (Ernest Hemingway)",
		"Il cuore ha le sue ragioni che la ragione non conosce. (Blaise Pascal)",
		"Se tu hai una mela, e io ho una mela, e ce le scambiamo, allora tu ed io abbiamo sempre una mela per uno. Ma se tu hai un\'idea, ed io ho un\'idea, e ce le scambiamo, allora abbiamo entrambi due idee. (George Bernard Shaw)",
		"Chi in cento battaglie riporta cento vittorie, non è il più abile in assoluto; al contrario, chi non dà nemmeno battaglia, e sottomette le truppe dell\'avversario, è il più abile in assoluto. (Sūnzǐ)",
		"Ci sedemmo dalla parte del torto visto che tutti gli altri posti erano occupati. (Bertolt Brecht)",
		"Guardo al futuro, a un tempo in cui l\'uomo progredirà verso qualcosa di più degno e più alto del suo stomaco, quando ci sarà una motivazione più sottile che spinga gli uomini all\'azione che quella di oggi, lo stomaco. Mantengo la mia convinzione della nobiltà e dell\'eccellenza del genere umano. Credo che la dolcezza spirituale e l\'altruismo avranno la meglio sulla grossolanità della gola. (Jack London)",
		"La prima cosa a sparire quando un paese viene trasformato in uno stato totalitario è la commedia e i comici. Poiché le persone ridono di noi, non credo che capiscano davvero quanto siamo essenziali per la loro salute mentale. (Groucho Marx)",
		"La libertà non sta nello scegliere tra bianco e nero, ma nel sottrarsi a questa scelta prescritta. (Theodor Adorno)",
		"Non c\'è alcuna grandezza là dove non vi sono la semplicità, il bene e la verità. (Lev Tolstoj, Guerra e pace)",
		"Finché, domestica o straniera, voi avete tirannide, come potete aver patria? La patria è la casa dell\'uomo, non dello schiavo. (Giuseppe Mazzini)",
		"Non vi sono né cattive erbe né cattivi uomini: vi sono soltanto cattivi coltivatori. (Victor Hugo)",
		"Non vi è cosa tanto facile che non sia difficile se la si fa contro voglia. (Publio Terenzio Afro)",
		"Ogni lettore, quando legge, è il lettore di se stesso. L\'opera dello scrittore è solo una specie di strumento ottico offerto al lettore per consentirgli di discernere ciò che forse, senza quel libro, non avrebbe potuto intravedere in se stesso. (Marcel Proust)",
		"La guerra in un primo momento è la speranza che a uno possa andar meglio, poi l\'attesa che all\'altro vada peggio, quindi la soddisfazione perché l\'altro non sta per niente meglio e infine la sorpresa perché a tutti e due va peggio. (Karl Kraus)",
		"Vivere insieme è un\'arte. (Thích Nhất Hạnh)",
		"La dignità dell\'uomo povero e oscuro ma laborioso ed onesto, è maggiore di tutte le altre, e va innanzi a tutte le vanità della terra. (Pietro Thouar)",
		"Chi salva una vita, salva il mondo intero. (Talmud)",
		"L\'amore coglie sfumature invisibili a un occhio indifferente e ne trae conseguenze infinite. (Stendhal)",
		"Per noi, servire è un privilegio [...]. Ci rendiamo conto che quello che facciamo è solo una goccia nell\'oceano, ma l\'oceano senza quella goccia sarebbe più piccolo. (Madre Teresa di Calcutta)",
		"Sii il cambiamento che vuoi vedere nel mondo. (Mahatma Gandhi)",
		"La pazienza è la più eroica delle virtù giusto perché non ha nessuna apparenza d\'eroico. (Giacomo Leopardi)",
		"Ho provato, ho fallito. Non importa, riproverò. Fallirò meglio. (Samuel Beckett)",
		"È un ottimo sport mattutino per un ricercatore mandare al diavolo ogni mattina prima di colazione un\'ipotesi prediletta: mantiene giovani. (Konrad Lorenz)",
		"Ciò che sfugge alla logica è quanto v\'è di più prezioso in noi stessi. (André Gide)",
		"Se guardi nel buio a lungo, c\'è sempre qualcosa. (William Butler Yeats)",
		"Chi lotta con i mostri deve guardarsi di non diventare, così facendo, un mostro. E se tu scruterai a lungo in un abisso, anche l\'abisso scruterà dentro di te. (Friedrich Nietzsche)",
		"La libertà [...] non consiste nell\'avere un padrone giusto, ma nel non averne alcuno. (Marco Tullio Cicerone)",
		"Voi volete dire allora che il mondo intero è la metafora di qualcosa? (Il postino)",
		"Sì come una giornata bene spesa dà lieto dormire, così una vita bene usata dà lieto morire. (Leonardo da Vinci)",
		"Le libertà sono tutte solidali. Non se ne offende una senza offenderle tutte. (Filippo Turati)",
		"La vita non è già destinata ad essere un peso per molti, e una festa per alcuni, ma per tutti un impiego, del quale ognuno renderà conto. (Alessandro Manzoni)",
		"Non essere amati è una semplice sfortuna; la vera disgrazia è non amare. (Albert Camus)",
		"La simpatia, oltre i confini umani, che vuol dire l\'umanità verso le bestie, sembra essere fra gli acquisti morali più tardivi. Non sembra che i selvaggi la provino tranne che per quegli animali che prediligono. [...] Questa virtù, una delle più nobili di cui l\'uomo sia fornito, sembra derivare per incidente da ciò che le nostre simpatie facendosi più tenere e più espansive e diffuse, vengono a riversarsi su tutti gli esseri senzienti. Appena questa virtù viene onorata e praticata da alcuni uomini, si diffonde mercé l\'istruzione e l\'esempio ai giovani. (Charles Darwin)",
		"Se riesci a non perdere la testa, quando tutti intorno la perdono, e se la prendono con te; se riesci a non dubitare di te stesso, quando tutti ne dubitano, ma anche a cogliere in modo costruttivo i loro dubbi; [...] il mondo è tuo, con tutto ciò che ha dentro, e, ancor di più, ragazzo mio, sei Uomo! (Rudyard Kipling)",
		"Baciami mille volte e ancora cento poi nuovamente mille e ancora cento e dopo ancora mille e dopo cento, e poi confonderemo le migliaia tutte insieme per non saperle mai, perché nessun maligno porti male sapendo quanti sono i nostri baci. (Gaio Valerio Catullo)",
		"A che ti giova insegnare agli altri [...], se intanto tu per primo non ascolti te stesso? (Francesco Petrarca)",
		"Solo sognando e restando fedeli ai sogni riusciremo a essere migliori e, se noi saremo migliori, sarà migliore il mondo. (Luis Sepúlveda)",
		"La natura ha assegnato a tutti ali squisite secondo necessità, ma sono davvero pochissimi coloro che sanno dispiegarle per solcare e battere quell\'aria che invita e si presta a essere battuta per volare non meno di quanto sembri opporsi a essere solcata: infatti dopo che con fatica l\'avrai smossa solcandola, questa, non ingrata, ti spingerà avanti sostenendoti. (Giordano Bruno)",
		"È una cosa stolta supplicare gli dei per ottenere ciò che uno è in condizione di procurarsi da se stesso. (Epicuro)",
		"Non c\'è mai stato, non ci sarà, né c\'è adesso un uomo che sia sempre biasimato o un uomo che sia sempre lodato. (Gautama Buddha)",
		"Non puoi giudicare nessuno al di là di quanto conosci di lui; ed è ben poco quel che tu ne conosci. (Khalil Gibran)",
		"Tu sarai amato, il giorno in cui potrai mostrare la tua debolezza, senza che l\'altro se ne serva per affermare la sua forza. (Cesare Pavese)",
		"Bisognerebbe dire la verità con garbo. Sarebbe meglio non dirla, se non si fosse capaci di farlo in modo cortese; intendendo con ciò che non c\'è verità in un uomo che non sappia controllare la propria lingua. (Mahatma Gandhi)",
		"Prendi posizione. La neutralità favorisce sempre l\'oppressore, non la vittima. (Elie Wiesel)",
		"Viviamo in questo mondo per imparare e per illuminarci l\'un l\'altro. (Wolfgang Amadeus Mozart)",
		"L\'educazione dovrebbe cominciare con l\'insegnare il valore della non violenza, che ha a che fare poi con tutto: con l\'essere vegetariano, col rispettare il mondo, col pensare che questa terra non te l\'han data a te, che è di tutti e tu non puoi impunemente metterti a tagliare e fare buchi. (Tiziano Terzani)",
		"Gli uomini malvagi non hanno bisogno che di una cosa per raggiungere i loro scopi, cioè che gli uomini buoni guardino e non facciano nulla. (John Stuart Mill)",
		"Certo sono più sapiente io di quest\'uomo, anche se poi, probabilmente, tutti e due non sappiamo proprio un bel niente; soltanto che lui crede di sapere e non sa nulla, mentre io, se non so niente, ne sono per lo meno convinto, perciò, un tantino di più ne so di costui, non fosse altro per il fatto che ciò che non so, nemmeno credo di saperlo. (Platone, attribuita a Socrate)",
		"Abbastanza spesso la gente mi considera pazzo quando faccio un salto invece di un passo, proprio come se tutti i salti fossero sbagliati e mai portassero uno in nessun posto. (Ezra Pound)",
		"La vita non è una corsa ma un tiro al bersaglio: non è il risparmio del tempo che conta, bensì la capacità di trovare un centro. (Susanna Tamaro)",
		"Fare del proprio meglio. Rifare. Ritoccare impercettibilmente ancora questo ritocco. «Correggendo le mie opere, – diceva Yeats, – correggo me stesso». (Marguerite Yourcenar)",
		"Si chiese, come aveva fatto parecchie volte in passato, se per caso non fosse pazzo. Forse, a ben pensarci, un pazzo non era che una minoranza formata da una sola persona. Un tempo era segno di follia credere che la terra girasse intorno al sole, oggi lo era il ritenere che il passato fosse immutabile. Poteva darsi che lui fosse il solo ad avere una simile convinzione, ed essendo il solo doveva per forza di cose essere pazzo. Tuttavia non lo disturbava granché il pensiero di essere pazzo: più orribile ancora era la possibilità che non lo fosse. (George Orwell, 1984)",
		"Un esperto è un uomo che ha fatto tutti gli errori che sia possibile compiere in un campo molto ristretto. (Niels Bohr)",
		"La salvezza dell\'uomo è nelle mani dei disadattati creativi. (Martin Luther King)",
		"Un\'anima meschina, sottrattasi all\'oppressione, opprimerà a sua volta. (Fëdor Dostoevskij)",
		"L\'ottimista vede opportunità in ogni pericolo, il pessimista vede pericolo in ogni opportunità. (Winston Churchill)",
		"Chi mente, se anche non viene scoperto, ha la punizione in sé medesimo; egli sente che tradisce un dovere e si degrada. (Silvio Pellico)",
		"La gioia di vivere è il miglior cosmetico per una donna. (Rosalind Russell)",
		"I regali fatti agli amici non sono preda del fato: avrai soltanto le ricchezze che hai donato. (Marco Valerio Marziale)",
		"Colui che potendo dire una cosa in dieci parole ne impiega dodici, io lo ritengo capace delle peggiori azioni. (Giosuè Carducci)",
		"È in ogni uomo di attendersi che forse la parola, una parola, possa trasformare la sostanza di una cosa. [...] È fede in una magia: che un aggettivo possa giungere dove non giunse, cercando la verità, la ragione; o che un avverbio possa recuperare il segreto che si è sottratto a ogni indagine. (Elio Vittorini)",
		"La cultura, si sa, costa, mentre l\'ignoranza è gratis (ecco perché è così diffusa). E io non mi sono lasciato sfuggire l\'occasione. Ma, attenti, non sono ignorante in un settore specifico, la mia ignoranza spazia in vari campi: io non so un po\' di tutto. Ho, insomma, quella che si dice una ignoranza enciclopedica. (Pino Caruso)",
		"Se c\'è un rimedio, perché te la prendi? E se non c\'è un rimedio, perché te la prendi? (proverbio cinese)",
		"L\'uomo è l\'unico animale che arrossisce. O dovrebbe arrossire. (Mark Twain)",
		"Nessun uomo è un\'isola, completo in se stesso; ogni uomo è un pezzo del continente, una parte del tutto. Se anche solo una zolla venisse lavata via dal mare, l\'Europa ne sarebbe diminuita, come se le mancasse un promontorio, come se venisse a mancare una dimora di amici tuoi, o la tua stessa casa. La morte di qualsiasi uomo mi sminuisce, perché io sono parte dell\'umanità. E dunque non chiedere mai per chi suona la campana: suona per te. (John Donne)",
		"Quando il viaggiatore si è seduto sulla sabbia della spiaggia e ha detto: \"Non c'è altro da vedere\", sapeva che non era vero. La fine di un viaggio è solo l\'inizio di un altro. Bisogna vedere quel che non si è visto, vedere di nuovo quel che si è già visto, vedere in primavera quel che si è visto in estate, vedere di giorno quel che si è visto di notte, con il sole dove la prima volta pioveva, vedere le messi verdi, il frutto maturo, la pietra che ha cambiato posto, l\'ombra che non c\'era. (José Saramago)",
		"Il genio è per l\'1% ispirazione e per il 99% sudore. (Thomas Edison)",
		"Ogni uomo porta l\'intera impronta della condizione umana. (Michel de Montaigne)",
		"Se potessi promettere qualcosa se potessi fidarmi di me stesso se di me non avessi anzi paura, padre, una cosa ti prometterei: di viver fortemente come te sacrificato agli altri come te e negandomi tutto come te, povero padre, per la fiera gioia di finir tristemente come te. (Camillo Sbarbaro)",
		"Chi prega è santo, ma chi fa, più santo. (Giovanni Pascoli)",
		"Primavera non bussa, lei entra sicura, come il fumo lei penetra in ogni fessura, ha le labbra di carne, i capelli di grano, che paura, che voglia che ti prenda per mano. Che paura, che voglia che ti porti lontano. (Fabrizio De André)",
		"Il tempo con il suo trascorrere insegna tutte le cose. (Eschilo)",
		"Finché si è scontenti di sé non tutto è perduto. (Emil Cioran)",
		"Dove non c\'è umorismo non c\'è umanità; dove non c\'è umorismo (questa libertà che si prende, questo distacco di fronte a se stessi) c\'è il campo di concentramento. (Eugène Ionesco)",
		"Il frutto dell\'amore è il servizio. Il frutto del servizio è la pace. (Madre Teresa di Calcutta)",
		"La giovanezza essendo a la voluttà inclinata non si piglia se non con l\'esca del piacere: perché fugge i rigidi maestri. (Marsilio Ficino)",
		"Gli uomini temono il pensiero più di qualsiasi cosa al mondo, più della rovina, più della morte stessa. Il pensiero è rivoluzionario e terribile. Il pensiero non guarda ai privilegi, alle istituzioni stabilite e alle abitudini confortevoli. Il pensiero è senza legge, indipendente dall\'autorità, noncurante dell\'approvata saggezza dell\'età. Il pensiero può guardare nel fondo dell\'abisso e non avere timore. Ma se il pensiero diventa proprietà di molti e non privilegio di pochi, dobbiamo finirla con la paura. (Bertrand Russell)",
		"Ciò che distingue l\'uomo immaturo è che vuole morire nobilmente per una causa, mentre ciò che distingue l\'uomo maturo è che vuole umilmente vivere per essa. (Wilhelm Stekel)",
		"Anche la vita è un istante soltanto, soltanto un dissolversi di noi stessi in tutti gli altri, come offertici in dono. (Boris Pasternak)",
		"Per fare un prato bastano un trifoglio, un\'ape, un trifoglio, un\'ape e un sogno. Può bastare il sogno se le api sono poche. (Emily Dickinson)",
		"È difficile camminare sul filo di un rasoio; così, dice il saggio, è aspro il cammino verso la salvezza. (Kaṭha Upaniṣad)",
		"Se mi batto con lo sterco è certo che vincitore o vinto finirò sempre imbrattato. (Giacomo Casanova)",
		"La saggezza della gente non innamorata a cui pare che un uomo di spirito dovrebbe essere infelice solo per una persona che lo meriti; pressappoco è come stupirsi che uno si degni di ammalarsi di colera a causa di un essere così piccolo come il bacillo virgola. (Marcel Proust)",
		"La grandezza dell\'uomo è nella decisione di essere più forte della sua condizione. (Albert Camus)",
		"A mio avviso tutti i nostri sconforti per le cose di cui manchiamo, scaturiscono dalla nostra ingratitudine per quelle che abbiamo. (Daniel Defoe)",
		"L\'attesa del piacere è essa stessa il piacere. (Gotthold Ephraim Lessing)",
		"Siamo angeli con un\'ala sola. Possiamo volare solo restando abbracciati. (Luciano De Crescenzo)",
		"La patria considerata nella sua morale e profonda significazione è il compiuto sodamento di ciascuno verso di tutti e di tutti verso ciascuno. (Terenzio Mamiani)",
		"Trovo che la televisione sia molto educativa. Ogni volta che qualcuno l\'accende, vado in un\'altra stanza a leggere un libro. (Groucho Marx)",
		"La cosa migliore è essere soli ma mai veramente soli. (Charles Bukowski)",
		"La posterità non intreccia ghirlande per gli imitatori. (Friedrich Schiller)",
		"Non reagire è una reazione: siamo altrettanto responsabili di ciò che non facciamo. (Jonathan Safran Foer)",
		"Giorno afoso, una cuccia e un cane alla catena. Poco più in là una ciotola ricolma d\'acqua. Ma la catena è corta e il cane non ci arriva. Aggiungiamo al quadretto ancora un elemento: le nostre sono molto più lunghe e meno visibili catene che ci fanno passare accanto disinvolti. (Wisława Szymborska)",
		"Segui il consiglio del tuo cuore, perché nessuno ti sarà più fedele di lui. (Siracide)",
		"Devo pur sopportare due o tre bruchi se voglio conoscere le farfalle. (Antoine de Saint-Exupéry)",
		"Secondo alcuni autorevoli testi di tecnica aeronautica, il calabrone non può volare a causa della forma e del peso del proprio corpo, in rapporto alla superficie alare. Ma il calabrone non lo sa e perciò continua a volare. (Igor\' Ivanovič Sikorskij)",
		"C\'è sempre tempo per lanciare una parola, ma non sempre per riprenderla. (Baltasar Gracián)",
		"Ma valeva la pena saper tutto questo, se non si sapeva l\'uno e il tutto, la cosa più importante di tutte, la sola cosa importante? (Hermann Hesse)",
		"O taci, o di\' cosa migliore del silenzio. (proverbio italiano)",
		"Tutto ciò che ci irrita negli altri può portarci a capire noi stessi. (Carl Gustav Jung)",
		"Ecco come bisogna essere! Bisogna essere come l\'acqua. Niente ostacoli – essa scorre. Trova una diga, allora si ferma. La diga si spezza, scorre di nuovo. In un recipiente quadrato, è quadrata. In uno tondo, è rotonda. Ecco perché è più indispensabile di ogni altra cosa. Niente esiste al mondo più adattabile dell\'acqua. E tuttavia quando cade sul suolo, persistendo, niente può essere più forte di lei. (attribuita a Laozi)",
		"I paurosi muoiono mille volte prima della loro morte, ma l\'uomo di coraggio non assapora la morte che una volta. (William Shakespeare, Giulio Cesare)",
		"La Terra ha abbastanza per i bisogni di tutti, ma non per l\'avidità di poche persone. (Mahatma Gandhi)",
		"Mentre stiamo parlando il tempo invidioso sarà già fuggito. Cogli il giorno presente confidando il meno possibile nel futuro. (Quinto Orazio Flacco)",
		"La nostra personalità è fragile, è molto più in pericolo che non la nostra vita; e i savi antichi, invece di ammonirci «ricordati che devi morire», meglio avrebbero fatto a ricordarci questo maggior pericolo che ci minaccia. (Primo Levi)",
		"La libertà è come l\'aria: ci si accorge di quanto vale quando comincia a mancare. (Piero Calamandrei)",
		"Sembravano traversie ed eran in fatti opportunità. (Giambattista Vico)",
		"Un vincitore è semplicemente un sognatore che non si è mai arreso. (Nelson Mandela)",
		"Ricordati che il miglior medico è la natura: guarisce i due terzi delle malattie e non parla male dei colleghi. (Galeno)",
		"Dobbiamo imparare a risvegliarci e a mantenerci desti, non con aiuti meccanici ma con una infinita speranza nell\'alba, che non ci abbandona neppure nel sonno più profondo. Non conosco nulla di più incoraggiante dell\'incontestabile capacità dell\'uomo di elevare la sua vita con uno sforzo cosciente. È bello sapere dipingere un certo quadro, o scolpire una statua e così rendere belli alcuni oggetti; ma è molto più degno di gloria scolpire e dipingere l\'atmosfera stessa e il mezzo con il quale guardiamo, cosa che possiamo fare moralmente. L\'arte più degna è influire sulle qualità del giorno. (Henry David Thoreau)",
		"Due cose riempiono l\'animo di ammirazione e venerazione sempre nuova e crescente, quanto più spesso e più a lungo la riflessione si occupa di esse: il cielo stellato sopra di me, e la legge morale in me. (Immanuel Kant)",
		"Ovunque l\'uomo porti il suo lavoro, vi lascia anche qualche cosa del suo cuore. (Henryk Sienkiewicz)",
		"Un uomo forte non ha bisogno del potere; un debole ne viene schiacciato. (Nicola II di Russia)",
		"Chi porta il paraocchi, si ricordi che del completo fanno parte il morso e la sferza. (Stanisław Jerzy Lec)",
		"Giove ci impose due bisacce: ci mise dietro quella piena dei nostri difetti e davanti, sul petto, quella con i difetti degli altri. Perciò non possiamo scorgere i nostri difetti e, non appena gli altri sbagliano, siamo pronti a biasimarli. (Fedro)",
		"L\'immaginazione governa il mondo. (Napoleone Bonaparte)",
		"Abbiamo fin troppe religioni per odiarci, ma non abbastanza per amarci l\'un l\'altro. (Jonathan Swift)",
		"L\'esempio non è la cosa che influisce di più sugli altri: è l\'unica cosa. (Albert Schweitzer)",
		"Lascia dormire il futuro come si merita. Se lo si sveglia prima del tempo, si ottiene un presente assonnato. (Franz Kafka)",
		"La libertà è la facoltà dell\'Uomo di valersi di tutte le sue forze morali e fisiche come gli piace, colla sola limitazione di non impedir agli altri di far lo stesso. (Francesco Mario Pagano)",
		"Vedi cose che esistono e ti chiedi \"perché\"? Ma io sogno cose non ancora esistite e chiedo \"perché no\"? (George Bernard Shaw)",
		"La filosofia è scritta in questo grandissimo libro che continuamente ci sta aperto innanzi a gli occhi (io dico l\'universo), ma non si può intendere se prima non s\'impara a intender la lingua, e conoscer i caratteri, ne\' quali è scritto. Egli è scritto in lingua matematica, e i caratteri son triangoli, cerchi, ed altre figure geometriche, senza i quali mezi è impossibile a intenderne umanamente parola; senza questi è un aggirarsi vanamente per un oscuro laberinto. (Galileo Galilei)",
		"Nessuno ha una memoria tanto buona da poter essere un perfetto bugiardo. (Abramo Lincoln)",
		"Soprattutto, siate sempre capaci di sentire nel più profondo qualsiasi ingiustizia commessa contro chiunque in qualunque parte del mondo. (Che Guevara)",
		"Ci sono due modi di diffondere luce: essere la candela oppure essere lo specchio che la riflette. (Edith Wharton)",
		"Un amico è qualcuno che ti conosce molto bene e, nonostante questo, continua a frequentarti. (Oscar Wilde)",
		"C\'è nei sogni, specialmente in quelli generosi, una qualità impulsiva e compromettente che spesso travolge anche coloro che vorrebbero mantenerli confinati nel limbo innocuo della più inerte fantasia. (Alberto Moravia)",
		"Assai acquista chi perdendo impara. (Michelangelo Buonarroti)",
		"La vera saggezza è nel pensare da pessimista, poiché la natura delle cose è ingiusta e crudele e la illusione è debolezza; ma, nella vita pratica e nella misura del possibile, agire da ottimista poiché nessuna energia, nessuno sforzo di bontà e di amore vanno mai interamente perduti. (Francesco Saverio Nitti)",
		"La dignità non consiste nel possedere onori ma nella coscienza di meritarli. (Aristotele)",
		"Se stai camminando per Greene Street e senti un rumore di zoccoli dietro di te, non voltarti aspettandoti di vedere una zebra. Aspettati un cavallo. (Theodore Woodward)",
		"Non riesco levarmi di mente lo scarto che c\'è fra idee e vita. Uno scarto permanente, per quanto noi cerchiamo di celarlo con lucida tenda. E non va. Le idee debbono sposarsi all\'azione; se in loro non vi è sesso, non vita, non c\'è azione. (Henry Miller)",
		"Colui che fa il bene agli altri è felice, ma disgraziato è colui che s\'attende il bene dagli altri. (Inayat Khan)",
		"Ciascuno deve custodire e santificare la propria anima nel modo e nel luogo a lui propri, senza invidiare il modo e il luogo degli altri. (Martin Buber)",
		"Non ci è permesso scegliere la cornice del nostro destino. Ma ciò che vi mettiamo dentro è sicuramente nostro. (Dag Hammarskjöld)",
		"Se il desiderio abbellisce tutte le cose su cui si posa, il desiderio dell\'ignoto abbellisce l\'universo. (Anatole France)",
		"La scienza è la somma totale di una grande moltitudine di misteri. È un argomento senza fine tra una grande moltitudine di voci. Assomiglia a Wikipedia molto più di quanto non assomigli all\'Enciclopedia Britannica. (Freeman Dyson)",
		"Una compagnia di porcospini, in una fredda giornata d\'inverno, si strinsero vicini, vicini, per evitare, col calore reciproco, di rimanere assiderati. Ben presto, però, sentirono gli aculei l\'uno dell\'altro; il dolore li costrinse ad allontanarsi di nuovo. Quando poi il bisogno di riscaldarsi li portò ancora a stare insieme, si ripeté il precedente inconveniente; di modo che venivano sballottati fra due mali, finché non trovarono una moderata distanza reciproca, che rappresentava per loro la migliore posizione. (Arthur Schopenhauer)",
		"Comprendendo la realtà noi la trasformiamo; penetrando con l\'intelligenza il male, noi lo dissolviamo. (Piero Martinetti)",
		"Imparate dal mio esempio, se non dalle mie parole, quanto sia pericoloso acquisire la conoscenza e quanto sia più felice l\'uomo convinto che il suo paese sia tutto il mondo, di colui che aspira a un potere più grande di quanto la natura non conceda. (Mary Shelley, Frankenstein)",
		"Il timore di perdere il potere corrompe chi lo detiene e la paura del castigo del potere corrompe chi ne è soggetto. (Aung San Suu Kyi)",
		"La morte sopravverrà a metterci in riposo, a toglierci dalle mani il compito a cui attendevamo; ma essa non può fare altro che così interromperci, come noi non possiamo fare altro che lasciarci interrompere, perché in ozio stupido essa non ci può trovare. (Benedetto Croce)",
		"Il tipografo che compone bene questa pagina che forse non gli piace. Una donna e un uomo che leggono le terzine finali di un certo canto. Chi accarezza un animale addormentato. Chi giustifica o vuole giustificare un male che gli hanno fatto. Chi è contento che sulla terra ci sia Stevenson. Chi preferisce che abbiano ragione gli altri. Tali persone, che si ignorano, stanno salvando il mondo. (Jorge Luis Borges)",
		"Non vediamo mai al di là delle nostre certezze e, cosa ancora più grave, abbiamo rinunciato all\'incontro, non facciamo che incontrare noi stessi in questi specchi perenni senza nemmeno riconoscerci. Se ci accorgessimo, se prendessimo coscienza del fatto che nell\'altro guardiamo solo noi stessi, che siamo soli nel deserto, potremmo impazzire. (Muriel Barbery)",
		"Non chiamare stolto nessuno tra voi, giacché in verità noi non siamo né saggi né stolti. Siamo verdi foglie sull\'albero della vita, e la vita stessa è al di là della saggezza e, certo, al di là della stoltezza. (Khalil Gibran)",
		"Dio, concedimi la serenità di accettare le cose che non posso cambiare, il coraggio per cambiare quelle che posso e la saggezza per riconoscerne la differenza. (Reinhold Niebuhr)",
		"Quando si gioca a palla le mosse di chi riceve devono essere in sintonia con quelle di chi lancia: così in un discorso c\'è sintonia tra chi parla e chi ascolta se entrambi sono attenti ai propri doveri. (Plutarco)",
		"L\'eroico ingegno si contenta più tosto di cascar o mancar degnamente e nell\'alte imprese, dove mostre la dignità del suo ingegno, che riuscir a perfezione in cose men nobili e basse. (Giordano Bruno)",
		"Non bisogna giudicare il buon Dio da questo mondo, perché è uno schizzo che gli è venuto male. (Vincent Van Gogh)",
		"L\'ottimista afferma che viviamo nel migliore dei mondi possibili, il pessimista teme che sia vero. (James Branch Cabell)",
		"L\'uomo ha un bel guardare ed abbracciare lo spazio; la natura intera non si compone per lui che di due o tre punti sensibili, ai quali tutta la sua anima converge. Togliete dalla vita il cuore che vi ama: che cosa vi resta? Ugualmente avviene della natura. Cancellate il luogo e la casa che i vostri pensieri cercano e che i vostri ricordi popolano, non scorgereste più che un vuoto immenso in cui lo sguardo s\'immerge senza trovar né fondo né riposo. Come si può stupire, dopo ciò, che le scene più sublimi della creazione siano contemplate con occhi ben diversi dai viaggiatori? Gli è che ciascuno porta con sé il suo punto di vista. Una nube sull\'anima vela e scolora più di una nube sull\'orizzonte. Lo spettacolo è nello spettatore. (Alphonse de Lamartine)",
		"Il bene si fa, ma non si dice. E certe medaglie si appendono all\'anima, non alla giacca. (Gino Bartali)",
		"La virtù, la sanità fisica, ogni bene e la divinità sono armonia: perciò anche l\'universo è costituito secondo armonia. Anche l\'amicizia è uguaglianza armonica. (Pitagora)",
		"Non è una mia fantasia che la vista del cielo, delle nubi, della luna e delle stelle mi renda tranquilla e paziente. È una medicina migliore della valeriana o del bromuro. La natura mi rende umile e pronta ad affrontare valorosamente ogni avversità. (Anna Frank)",
		"\"È vero, principe, che lei una volta ha detto che la \'bellezza\' salverà il mondo? State a sentire, signori,\" gridò ad alta voce, rivolgendosi a tutti, \"il principe sostiene che la bellezza salverà il mondo! E io sostengo che questi giocondi pensieri gli vengono in testa perché è innamorato. Signori, il principe è innamorato [...] Ma quale bellezza salverà il mondo? (Fëdor Dostoevskij, L\'idiota)",
		"Attraverso le asperità si giunge alle stelle. Per aspera sic itur ad astra. (attribuita a Lucio Anneo Seneca)",
		"L\'uomo ha ricordi, rimorsi e rancori che si accumulano dentro di lui come strati di polvere finché gli impediscono di ricevere la luce e la vita che discende dal cielo. Il creato, invece, si rinnova costantemente. Se il cielo si rannuvola, poi si rasserena. Il sole tramonta, ma ogni mattino rinasce. Le stelle o la luna non recano le tracce del tempo. La continuità del processo di creazione della natura non appare mai tanto ovvia come all\'alba, quando cade la rugiada, gli uccellini cinguettano, il fiume s\'infiamma, l\'erba è umida e fresca. Felice è l\'uomo che sa rinnovarsi insieme al creato. (Isaac Bashevis Singer)",
		"Ciò che turba gli uomini non sono le cose, ma le opinioni che essi hanno delle cose. (Epitteto)",
		"Quando un uomo è audace senza senno ne riceve danno, quando invece con senno ne trae vantaggio. (Platone, attribuita a Socrate)",
		"Siamo qui, nell\'oscurità, sospesi tra la poesia delle lucciole e il fuoco divampante delle stelle. (Susanna Tamaro)",
		"Dall\'elefante alla pulce, e dalla pulce alla molecola sensibile e vivente, che costituisce l\'origine di ogni cosa, non c\'è un punto in tutta la natura che non soffra o non goda. (Denis Diderot)",
		"Gli uomini sono nati gli uni per gli altri: dunque, insegna loro o sopportali. (Marco Aurelio)",
		"In generale la grandezza dell\'ingegno non garantisce mai dall\'assurdità delle opinioni abbracciate. (Eulero)",
		"Che v\'è di buono in tutto questo, o Vita, ahimè? RISPOSTA Che tu sei qui – che esistono la vita e l\'individuo, che il potente spettacolo continua, e che tu puoi contribuirvi con un tuo verso. (Walt Whitman)",
		"Cercate di lasciare questo mondo un po\' migliore di come l\'avete trovato. (Robert Baden-Powell)",
		"La disperazione più grave che possa impadronirsi d\'una società è il dubbio che vivere rettamente sia inutile. (Corrado Alvaro)",
		"Quando non si può attaccare il ragionamento, si attacca il ragionatore. (Paul Valéry)",
		"Errare è umano, perdonare è divino. (Alexander Pope)",
		"Nessuno ha il diritto di fermarsi e provare disperazione. C\'è troppo da fare. (Dorothy Day)",
		"È molto più facile [...] essere un eroe che un galantuomo. Eroi si può essere una volta tanto; galantuomini, si dev\'esser sempre. (Luigi Pirandello)",
		"Un bacio può essere una virgola, un punto interrogativo o un punto esclamativo. È una fondamentale regola di lettura che ogni donna dovrebbe conoscere. (Mistinguett)",
		"Felicità raggiunta, si cammina per te sul fil di lama. Agli occhi sei barlume che vacilla, al piede, teso ghiaccio che s\'incrina; e dunque non ti tocchi chi più t\'ama. (Eugenio Montale)",
		"Tutti gli uomini sarebbero dunque necessariamente uguali, se fossero senza bisogni. La miseria connessa alla nostra specie subordina un uomo a un altro uomo; non l\'ineguaglianza è la vera disgrazia, ma la dipendenza. (Voltaire)",
		"Quando io penso a te giurerei che il Nilo nasce dal mio cuore. (Riccardo Mannerini)",
		"Quando viene dichiarata una guerra, la prima vittima è la Verità. (Arthur Ponsonby)",
		"Il giorno in cui i contadini saranno educati nel vero, i tiranni e gli schiavi saranno impossibili sulla terra. (Giuseppe Garibaldi)",
		"Solo un cambiamento dell\'atteggiamento individuale potrà portare con sé un rinnovamento dello spirito delle nazioni. Tutto comincia con l\'individuo. (Carl Gustav Jung)",
		"L\'uomo che lotta per ciò che egli ritiene giusto, è libero. Per contro si può vivere nel paese più democratico della terra, ma se si è interiormente pigri, ottusi, servili, non si è liberi; malgrado l\'assenza di ogni coercizione violenta, si è schiavi. Questo è il male, non bisogna implorare la propria libertà dagli altri. La libertà bisogna prendersela, ognuno la porzione che può. (Ignazio Silone)",
		"Quando vi svegliate al mattino, le cattiverie e i pensieri malvagi con i quali vi siete coricati sono stati ripiegati con cura e sistemati in una zona remota della vostra piccola mente, e in cima, ben esposti e aerati, restano i pensieri più dolci, pronti per essere indossati. (J. M. Barrie)",
		"La verità non è sempre bella, ma la fame di verità sì. (Nadine Gordimer)",
		"Soltanto una vita vissuta per gli altri è una vita che vale la pena vivere. (Albert Einstein)",
		"Il fatto che l\'uomo sia capace d\'azione significa che da lui ci si può attendere l\'inatteso, che è in grado di compiere ciò che è infinitamente improbabile. E ciò è possibile solo perché ogni uomo è unico e con la nascita di ciascuno viene al mondo qualcosa di nuovo nella sua unicità. (Hannah Arendt)",
		"Il fatto che gli uomini non imparino molto dalla storia è la lezione più importante che la storia ci insegna. (Aldous Huxley)",
		"Il tempo che hai perso per la tua rosa è ciò che fa la tua rosa tanto importante. (Antoine de Saint-Exupéry)",
		"Non bisogna toccare gl\'idoli: la doratura ci rimane sulle dita. (Gustave Flaubert)",
		"La cosiddetta \"scienza\", di cui mi occupo, non è altro che l’espressione della Volontà Suprema, che mira ad avvicinare le persone tra loro al fine di aiutarli a capire meglio e a migliorare se stessi. (Guglielmo Marconi)",
		"I campioni sono quelli che vogliono lasciare il loro sport in condizioni migliori rispetto a quando hanno iniziato a praticarlo. (Arthur Ashe)",
		"C\'è chi dice sia un esercito di cavalieri, c\'è chi dice sia un esercito di fanti, c\'è chi dice sia una flotta di navi, la cosa più bella sulla nera terra, io invece dico che è ciò che si ama. (Saffo)",
		"Siamo pronti a contraddire senza ostinazione, ed a lasciare, senza adirarci, che altri ci contraddica. (Marco Tullio Cicerone)",
		"Non datemi consigli: so sbagliare da me. (Dino Segre)",
		"Essere indulgenti verso gli altri, severi verso se stessi è un consiglio banale; nell\'esistenza è la sola regola da seguire. (Marcel Proust)",
		"La Terra è la culla dell\'Umanità, ma non si può vivere per sempre in una culla. (Konstantin Ėduardovič Ciolkovskij)",
		"Ci sono soltanto due possibili conclusioni: se il risultato conferma le ipotesi, allora hai appena fatto una misura; se il risultato è contrario alle ipotesi, allora hai fatto una scoperta. (Enrico Fermi)",
		"Un congedo opportuno lascia dietro una porta sempre aperta. (Erri De Luca)",
		"Avendo meditato la dolcezza e la pietà, ho dimenticato la differenza tra me e gli altri. (Milarepa)",
		"In questo mondo quotidiano, che somiglia tanto al libro delle Mille e Una Notte, non c\'è un solo gesto che non corra il rischio di essere un\'operazione di magia. (Jorge Luis Borges)",
		"I piccoli stati prosperano con la concordia, con la discordia vanno in rovina i più grandi. (Gaio Sallustio Crispo, attribuita a Micipsa)",
		"Non aver paura della perfezione: non la raggiungerai mai. (Salvador Dalí)",
		"Non aspettare il momento opportuno: crealo. (George Bernard Shaw)",
		"Impara tutto. Vedrai che in seguito nulla sarà superfluo. La conoscenza ristretta non è gioiosa. (Ugo di San Vittore)",
		"Il Cielo non prende niente senza ripagare smisuratamente. (Edith Stein)",
		"L\'uomo che pratica una sola classe sociale, è come lo studioso che non legge altro che un libro. (Edmondo De Amicis)",
		"Meglio fare e pentere, che starsi e pentersi. (Giovanni Boccaccio)",
		"Che l\'Essere risplendente, in cui si dissolvono i mondi e da cui un giorno rinasceranno, ci conceda la luce dell\'intelligenza. (Śvetāśvatara Upaniṣad)",
		"Non importa quante volte cadi. Quello che conta è la velocità con cui ti rimetti in piedi. (Joe Biden)",
		"La chiave di ogni uomo è il suo pensiero. Benché egli possa apparire saldo e autonomo, ha un criterio cui obbedisce, che è l\'idea in base alla quale classifica tutte le cose. Può essere cambiato solo mostrandogli una nuova idea che sovrasti la sua. (Ralph Waldo Emerson)",
		"Beati i misericordiosi, perché troveranno misericordia. (Gesù, Discorso della Montagna)",
		"Essere una cosa sola con tutto ciò che vive, far ritorno, beatamente dimentichi di se stessi, nel seno universale della natura, ecco il vertice di ogni pensiero e di ogni gioia. (Friedrich Hölderlin)",
		"Lo so: tutti i grandi uomini, in principio, furono incompresi; ma io non sono un grande uomo e vorrei essere compreso subito. (Jules Renard)",
		"Gli esseri umani non nascono sempre il giorno in cui le loro madri li danno alla luce, ma la vita li costringe ancora molte altre volte a partorirsi da sé. (Gabriel García Márquez)",
		"Ogni grande errore ha un momento a metà strada, una frazione di secondo in cui si può annullare e forse rimediare. (Pearl S. Buck)",
		"Voi pensate: i tempi sono cattivi, i tempi sono pesanti, i tempi sono difficili. Vivete bene e muterete i tempi. (Sant\'Ambrogio)",
		"Il sogno di uno solo è l\'illusione, l\'apparenza; il sogno di due è già la verità, la realtà. (Miguel de Unamuno)",
		"La maggioranza che si rassegna è colpevole. La minoranza ha il diritto di richiamarla. (Giovanni Passannante)",
		"Ovunque nel mondo, in qualsiasi posto il mio pensiero vada o si arresti, trova fedeli e operosi ponti, come eterno e mai soddisfatto desiderio dell\'uomo di collegare, pacificare e unire tutto ciò che appare davanti al nostro spirito, ai nostri occhi, ai nostri piedi, affinché non ci siano divisioni, contrasti, distacchi. (Ivo Andrić)",
		"Disapprovo quello che dici, ma difenderò fino alla morte il tuo diritto a dirlo. (Evelyn Beatrice Hall)",
		"Non credete mai a prima vista all\'infelicità degli uomini. Chiedetegli se riescono ancora a dormire... Se sì, va tutto bene. Basta quello. (Louis-Ferdinand Céline)",
		"Il valore non serve a nulla quando non si accompagna alla giustizia, e se tutti gli uomini fossero giusti, non ci sarebbe bisogno di essere valorosi. (Agesilao II)",
		"Tutte le volte che mi mostrai pronta ad accettarle, le prove si cambiarono in bellezza. (Etty Hillesum)",
		"Il miglior riconoscimento per la fatica fatta non è ciò che se ne ricava, ma ciò che si diventa grazie a essa. (John Ruskin)",
		"Il mondo è un bel libro, ma poco serve a chi non lo sa leggere. (Carlo Goldoni)",
		"La ricerca della verità è possibile soltanto se parliamo chiaramente e semplicemente ed evitiamo tecnicismi e complicazioni non necessari. Dal mio punto di vista, mirare alla semplicità e alla chiarezza è un dovere morale degli intellettuali: la mancanza di chiarezza è un peccato e la pretenziosità è un delitto. (Karl Popper)",
		"Non si è mai troppo poveri per donare una carezza. (Romano Battaglia)",
		"Quando sei in partiti difficili, o in cose che ti sono moleste, allunga e aspetta tempo quanto puoi, perché quello spesso ti illumina o ti libera. (Francesco Guicciardini)",
		"Forse non si desiderava tanto essere amati quanto essere capiti. (George Orwell, 1984)",
		"Ognuno di noi è schiavo di quel che dice e padrone di quel che tace. (Arturo Pérez-Reverte)",
		"Quelli che non sanno ricordare il passato sono condannati a ripeterlo. (George Santayana)",
		"Come diceva quella ragazza sgomenta al suo ragazzo: — Perché non sei anticonformista anche tu, come tutti gli altri? (Giuseppe Pontiggia)",
		"Ciò che seminai nell\'ira crebbe in una notte rigogliosamente ma la pioggia lo distrusse. |Ciò che seminai con amore germinò lentamente maturò tardi ma in benedetta abbondanza. (Peter Rosegger)",
		"Fermezza di fronte al destino, grazia nella sofferenza, non vuol dire semplicemente subire: è un\'azione attiva, un trionfo positivo. (Thomas Mann)",
		"Guarda guarda, hai comprato per il pranzo le cose [cervella e colli] con cui noi politici giochiamo a palla. (Stratocle)",
		"Chi ti ama c\'è sempre, c\'è prima di te, prima di conoscerti. (Margaret Mazzantini)",
		"Senza amore l\'acquisizione della conoscenza non fa che aumentare la confusione e condurci all\'autodistruzione. (Jiddu Krishnamurti)",
		"Guarda i girasoli: s\'inchinano al sole, ma se vedi uno che è inchinato un po\' troppo significa che è morto. Tu stai servendo, però non sei un servo. Servire è l\'arte suprema. Dio è il primo servitore; Lui serve gli uomini, ma non è servo degli uomini. (La vita è bella)",
		"Sii gentile, ogni persona che incontri sta combattendo una dura battaglia. (Ian Maclaren)",
		"Quanto può dirsi, si può dir chiaro; e su ciò, di cui non si può parlare, si deve tacere. (Ludwig Wittgenstein)",
		"Lo sforzo di capire l\'universo è tra le pochissime cose che innalzano la vita umana al di sopra del livello di una farsa, conferendole un po\' della dignità di una tragedia. (Steven Weinberg)",
		"Se non è rispettata la giustizia, che cosa sono gli Stati se non delle grandi bande di ladri? Perché anche le bande dei briganti che cosa sono se non dei piccoli Stati? (Agostino d\'Ippona)",
		"Fermare la diffusione del sapere è uno strumento di controllo per il potere perché conoscere è saper leggere, interpretare, verificare di persona e non fidarsi di quello che ti dicono. La conoscenza ti fa dubitare. Soprattutto del potere. Di ogni potere. (Dario Fo)",
		"Per concludere, insegnate al vostro allievo ad amare tutti gli uomini, anche quelli che disprezzano i loro simili; fate in modo che non si rinchiuda in nessuna classe sociale, ma si ritrovi in tutte; dinanzi a lui parlate del genere umano con tenerezza, con pietà, ma giammai con disprezzo. O uomo, non disonorare l\'uomo. (Jean-Jacques Rousseau)",
		"L\'altro uomo è a noi un\'immagine di come siamo noi; se io, anche nel silenzio e nella solitudine della mente, rispetto l\'immagine di un uomo, affermo in quel momento stesso la mia dignità di uomo, rendo omaggio all\'essere spirituale in lui e in me. Chi non rispetta un altro, in realtà non rispetta nemmeno se stesso. (Aldo Capitini)",
		"Esprimi il tuo pensiero in modo conciso perché sia letto, in modo chiaro perché sia capito, in modo pittoresco perché sia ricordato e, soprattutto, in modo esatto perché i lettori siano guidati dalla sua luce. (Joseph Pulitzer)",
		"Non c\'è e non ci può essere un\'arte che non si fondi sulla verità. (anonimo spartano)",
		"Tutti coloro che si occupano di insegnamento dovrebbero ricordare continuamente l\'antico motto latino «ludendo docere», cioè «insegnare divertendo». Se si riesce infatti a inserire l\'aspetto del «gioco» (nel senso dell\'«interesse») eccitando così le motivazioni individuali e accendendo i cervelli, si riesce a moltiplicare in modo altissimo l\'efficienza dell\'informazione, dell\'insegnamento, della comunicazione. Perché l\'interessato «ci sta». È stimolato, partecipa, ricorda. E impara. (Piero Angela)",
		"Il male immaginario è romantico, variato; il male reale tetro, monotono, desertico, noioso. Il bene immaginario è noioso; il bene reale è sempre nuovo, meraviglioso, inebbriante. (Simone Weil)",
		"L\'uomo più ricco è quello i cui piaceri sono più a buon mercato. (David Henry Thoreau)",
		"Le guerre appaiono inevitabili, lo appaiono sempre quando per anni non si è fatto nulla per evitarle. (Gino Strada)",
		"All\'amico si deve dire la verità; senza di essa il nome di amicizia non vale più nulla. (Aelredo di Rievaulx)",
		"Della vita non bisogna temere nulla. Bisogna solo capire. (Marie Curie)",
		"In tutta la vita non c\'è cosa più importante da fare che chinarsi perché un altro, cingendoti il collo, possa rialzarsi. (Annalena Tonelli)",
		"L\'amore consiste in questo, che due solitudini si proteggono a vicenda, si toccano, si salutano. (Rainer Maria Rilke)",
		"Essere capiti vuol dire essere presi e accettati per quello che siamo. (Natalia Ginzburg)",
		"Conviene all\'umanità di un maestro, mettere i propri discepoli in guardia contro se stesso. (Friedrich Nietzsche)",
		"Quando la casa piglia fuoco non è il momento di scaldarsi. Quant ch\'e ciape fuc la ciase, no bisugne scialdarsi. (proverbio friulano)",
		"Meglio accendere una candela che maledire l\'oscurità. (proverbio cinese)",
		"Quand\'ero figlio io, comandavano i padri. Ora, che sono padre, comandano i figli. La mia è una generazione che non ha mai contato nulla. (Pino Caruso)",
		"Nulla denota uno schiavo se non la dipendenza dalla volontà di un altro. (Algernon Sidney)",
		"Tutte le cose più grandi che conosciamo ci sono venute dai nevrotici. Sono loro e solo loro che hanno fondato religioni e hanno creato magnifiche opere d\'arte. Mai il mondo sarà conscio di quanto deve loro, e nemmeno di quanto essi abbiano sofferto per poter elargire i loro doni. (Marcel Proust)",
		"Non mi sentivo chiamato a lasciare il mondo e a ritirarmi in un convento, ma a vivere nel mondo ed amare le cose del mondo, non per esse stesse, per l\'Infinito che è in loro. Se in quei momenti di estasi fossi realmente stato tutt\'uno con l\'Assoluto e se ciò che dicevano era vero, niente poteva toccarmi, e, uscito dal karma della mia vita presente, non sarei più tornato in questo mondo. Quel pensiero mi sconcertò. Desideravo vivere di nuovo e poi di nuovo ancora. Ero pronto ad accettare qualunque genere di vita, anche se piena di dolori e sofferenze; sentivo che solo una serie infinita di vite poteva soddisfare la mia avidità, il mio vigore e la mia curiosità. (William Somerset Maugham)",
		"Io nacqui a debellar tre mali estremi; tirannide, sofismi, ipocrisia [...]. Carestie, guerre, pesti, invidia, inganno, ingiustizia, lussuria, accidia, sdegno tutti a que\' tre gran mali sottostanno che nel cieco amor proprio, figlio degno d\'ignoranza, radice e fomento hanno. (Tommaso Campanella)",
		"Fate tutto il bene che potete con tutti i mezzi che potete, in tutti i modi che potete, in tutti i luoghi che potete, tutte le volte che potete, a tutti quelli che potete, sempre, finché potrete. (John Wesley)",
		"Minorità è l\'incapacità di valersi del proprio intelletto senza la guida di un altro. Imputabile a sé stesso è questa minorità se la causa di essa non dipende da difetto di intelligenza, ma dalla mancanza di decisione e del coraggio di far uso del proprio intelletto senza essere guidati da un altro. Sapere aude! Abbi il coraggio di servirti della tua propria intelligenza! (Immanuel Kant)",
		"Abbiamo conquistato tante terre proprio perché coltiviamo noi stessi, non i campi. (Anassandrida II)",
		"Gli eventi contrari a ciò che dalla nostra utilità è richiesto, li sopporteremo di buon animo, se siamo consapevoli che abbiamo compiuto il nostro dovere, che la nostra potenza non poteva giungere a evitarli, e che noi siamo parte di tutta la natura, di cui seguiamo l\'ordine. (Baruch Spinoza, Ethica)",
		"La salute non analizza se stessa e neppure si guarda allo specchio. Solo noi malati sappiamo qualche cosa di noi stessi. (Italo Svevo)",
		"Non sono niente. Non sarò mai niente. Non posso voler essere niente. A parte ciò, ho in me tutti i sogni del mondo. (Fernando Pessoa)",
		"Nulla, dunque, di voi tenete per voi, affinché vi accolga tutti Colui che a voi si dà tutto. (Francesco d\'Assisi)",
		"L\'unico incoraggiamento che posso dare ai giovani, e che regolarmente gli do, è questo: \"Battetevi sempre per le cose in cui credete. Perderete, come le ho perse io, tutte le battaglie. Una sola potete vincerne: quella che s\'ingaggia ogni mattina, quando ci si fa la barba, davanti allo specchio. Se vi ci potete guardare senza arrossire, contentatevi\". (Indro Montanelli)",
		"Una montagna è come l\'istruzione: quanto più alta l\'ascesa, tanto più esteso il panorama. (Christiaan Barnard)",
		"«Qui siamo tutti matti. Io sono matto. Tu sei matta». «Come lo sai che sono matta?» disse Alice. «Per forza,» disse il Gatto: «altrimenti non saresti venuta qui». (Lewis Carroll)",
		"Facile a scorgere è l\'errore altrui, difficile è, invece, il proprio. (Gautama Buddha)",
		"Ricordando la propria esistenza, s\'accorse di avere sbagliato tutto – tutto. La sua era una vita – come si suol dire, rovinata. Ma siccome neppure agli inizi era stata un gran che, perché prendersela? (Saul Bellow)",
		"Tu non sei quello che sembri nei momenti di tristezza. Sei molto di più. (Paulo Coelho)",
		"Ci son più cose in cielo e in terra, Orazio, che non sogni la tua filosofia. (William Shakespeare, Amleto)",
		"Quale governo, si domanda, è il migliore? Quello che ci insegna a governarci da soli. (Johann Wolfgang von Goethe)",
		"Quando si ha una cosa, questa può essere portata via. [...] Ma quando si dà una cosa, questa è data. Nessun ladro può prendertela. (James Joyce)",
		"Comunque, è sempre infinitamente più difficile essere semplici che essere complicati. (Giovannino Guareschi)",
		"Odiare è come bere veleno sperando che un altro muoia. (Anonimo)",
		"Sii filosofo; ma in mezzo a tutta la tua filosofia, sii sempre un uomo. (David Hume)",
		"Esperienza è il nome che ciascuno dà ai propri errori. (Oscar Wilde)",
		"Dopo millenni di odi e di guerre per lo meno dovremmo avere imparato questo: che il dolore non ha bandiera. (Dacia Maraini)",
		"Dei tiranni nessuno mai, dopo morto, è ritornato in vita, mentre molte città, anche dopo essere state rase al suolo, hanno riacquistato vigore e potenza. (Iperide)",
		"E se la gente vede che sai suonare, be\", ti tocca suonare, per tutta la vita. (Edgar Lee Masters)",
		"Partono tutti incendiari e fieri ma quando arrivano sono tutti pompieri. (Rino Gaetano)",
		"Se ho fatto qualcosa di buono, questo sarà il mio monumento; se no, a che scopo commissionare statue su statue a scalpellini che non valgono nulla? (ultime parole di Agesilao II)",
		"Chi ti loda, s\'incensa. (Camillo Sbarbaro)",
		"Ho sentito un suono di catene che si rompono. È nato un uomo. (Vicente Huidobro)",
		"Felice chi poté conoscere le cagioni delle cose. (Publio Virgilio Marone)",
		"Sono un uomo e nulla di ciò che è umano mi è estraneo. Homo sum, humani nihil a me alienum puto. (Publio Terenzio Afro)",
		"Non vi può essere vera libertà senza giustizia sociale, come non vi può essere vera giustizia sociale senza libertà. [...] Si può considerare veramente libero un uomo che ha fame, che è nella miseria, che non ha lavoro, che è umiliato perché non sa come mantenere i suoi figli e educarli? Questo non è un uomo libero. Sarà libero di bestemmiare, di imprecare, ma questa non è la libertà che intendo io. (Sandro Pertini)",
		"Perché tu possa ascoltarmi le mie parole si fanno sottili, a volte come impronte di gabbiani sulla spiaggia. (Pablo Neruda)",
		"La guerra è sempre stata il principale divertimento dell\'umanità. Gli altri divertimenti sono un surrogato della guerra. (Halldór Laxness)",
		"Il vocabolo crisi indica oggi il momento in cui medici, diplomatici, banchieri e tecnici sociali di vario genere prendono il sopravvento e vengono sospese le libertà. Come i malati, i paesi diventano casi critici. Crisi, la parola greca che in tutte le lingue moderne ha voluto dire «scelta» o «punto di svolta», ora sta a significare: «Guidatore, dacci dentro!». [...] Ma «crisi» non ha necessariamente questo significato. Non comporta necessariamente una corsa precipitosa verso l\'escalation del controllo. Può invece indicare l\'attimo della scelta, quel momento meraviglioso in cui la gente all\'improvviso si rende conto delle gabbie nelle quali si è rinchiusa e della possibilità di vivere in maniera diversa. (Ivan Illich)",
		"Non c\'è migliore specchio dell\'amico vecchio. (proverbio toscano)",
		"Venuta la sera, mi ritorno in casa, et entro nel mio scrittoio; et in su l\'uscio mi spoglio quella veste cotidiana, piena di fango, et di loto, et mi metto panni reali et curiali; et rivestito condecentemente entro nelle antique corti degli antiqui huomini, dove, da loro ricevuto amorevolmente, mi pasco di quel cibo, che solum è mio, et che io nacqui per lui; dove io non mi vergogno parlare con loro, et domandarli della ragione delle loro actioni; et quelli per loro humanità mi rispondono; et non sento per 4 hore di tempo alcuna noia, sdimenticho ogni affanno, non temo la povertà, non mi sbigottisce la morte; tucto mi transferisco in loro. (Niccolò Machiavelli)",
		"Il miglior modo di onorare i santi è di imitarli. (Erasmo da Rotterdam)",
		"Le foglie stanno volando via dal mondo e sopra c\'erano dei messaggi e degli enigmi che non abbiamo decifrato. (Guido Ceronetti)",
		"L\'astronomia ci ha insegnato che non siamo il centro dell\'universo [...]. Siamo solo un minuscolo pianeta attorno a una stella molto comune. Noi stessi, esseri intelligenti, siamo il risultato dell\'evoluzione stellare, siamo fatti della materia degli astri. (Margherita Hack)",
		"A me piacciono troppe cose e io mi ritrovo sempre confuso e impegolato a correre da una stella cadente all\'altra finché non precipito. (Jack Kerouac)",
		"Aveva la coscienza pulita. Mai usata. (Stanisław Jerzy Lec)",
		"Attira la fortuna chi si rende conto di quella che ha già. (Massimo Gramellini)",
		"Nessuno può farvi sentire inferiori senza il vostro consenso. (attribuita a Eleanor Roosevelt)",
		"La stessa aquila, destinata a salire così in alto e a vedere tanto da lontano, comincia la vita nei crepacci della sua roccia e non vede in gioventù che gli orli aridi, spesso fetidi, del suo nido. (Alphonse de Lamartine)",
		"Scrivere è un modo di parlare senza essere interrotti. (Jules Renard)",
		"Là dove sono le belle parole e un\'apparenza perfetta, raramente ha sede il bene. (Confucio)",
		"Le risposte sono sempre limitate, provvisorie, insoddisfacenti. Le domande invece sono il vero motore dell\'attività mentale: un uomo che non si pone domande, o che si contenta delle risposte, non va molto lontano. L\'uomo deve dubitare: il dubbio è un atteggiamento di ricerca, di esplorazione: la certezza, soprattutto quella ideologica o dogmatica, possono forse renderlo più integrato, e in un certo senso più felice, ma con un costo intellettuale molto elevato, che è quello della sua rinuncia a dubitare, esplorare, e quindi pensare. (Piero Angela)",
		"Ho parlato a una capra. Era sola sul prato, era legata. Sazia d\'erba, bagnata dalla pioggia, belava. Quell\'uguale belato era fraterno al mio dolore. Ed io risposi, prima per celia, poi perché il dolore è eterno, ha una voce e non varia. (Umberto Saba)",
		"E quanto intendo più, tanto più ignoro. (Tommaso Campanella)",
		"La gente può non amare il formaggio putrido o gli starnottini marci o altri cibi apprezzati dai gastronomi di gusto pervertito, ma il pane e la frutta sono buoni solo quando piacciono alla gente. La stessa cosa vale per l\'arte: l\'arte pervertita può essere incomprensibile alla gente, ma l\'arte buona è sempre comprensibile a tutti. (Lev Tolstoj)",
		"Si dice che la verità è destinata a soffrire, ma non si estingue mai. (Tito Livio, attribuita a Quinto Fabio Massimo)",
		"Quando perdiamo il diritto a essere diversi, perdiamo il privilegio di essere liberi. (Charles Evans Hughes)",
		"Ma io sono un uomo che preferisce perdere piuttosto che vincere con modi sleali e spietati. Grave colpa da parte mia, lo so! E il bello è che ho la sfacciataggine di difendere tale colpa, di considerarla quasi una virtù… (Pier Paolo Pasolini)",
		"Avere il coraggio di dire ai giovani che essi sono tutti sovrani, per cui l\'obbedienza non è ormai più una virtù, ma la più subdola delle tentazioni, che non credano di potersene far scudo né davanti agli uomini né davanti a Dio, che bisogna che si sentano ognuno l\'unico responsabile di tutto. (Lorenzo Milani)",
		"Chi è pronto a dar via le proprie libertà fondamentali per comprarsi briciole di temporanea sicurezza, non merita né la libertà né la sicurezza. (Benjamin Franklin)",
		"Vagliate tutto, trattenete ciò che è buono. (Paolo di Tarso)",
		"Non misurare mai l\'altezza del monte prima d\'aver raggiunto la cima. Allora vedrai quanto era basso. (Dag Hammarskjöld)",
		"Non chiedete cosa possa fare il paese per voi: chiedete cosa potete fare voi per il paese. (John Fitzgerald Kennedy)",
		"Cercate sempre di rendervi conto del punto di vista dell\'altro prima di discutere o di litigare con lui, e novantanove volte su cento finirete con l\'essere in buoni rapporti con lui. (Robert Baden-Powell)",
		"Noi valiamo quanto le nostre parole. Se le azioni non coincidono con le parole, il nostro valore come persone è sminuito. (Julia Butterfly Hill)",
		"I morti che ci hanno fatto del bene, si ricompensano guardando in faccia i vivi. (Vasco Pratolini)",
		"Quel principio che ha come qualità la coscienza è presente indifferentemente in tutti i corpi, sicché colui che mediti come il tutto sia essenziato di esso, diventa vincitore del mondo. (Vijñānabhairava Tantra)",
		"La paura è normale che ci sia, in ogni uomo, l\'importante è che sia accompagnata dal coraggio. (Paolo Borsellino)",
		"L\'inferno dei viventi non è qualcosa che sarà; se ce n\'è uno, è quello che è già qui, l\'inferno che abitiamo tutti i giorni, che formiamo stando insieme. Due modi ci sono per non soffrirne. Il primo riesce facile a molti: accettare l\'inferno e diventarne parte fino al punto di non vederlo più. Il secondo è rischioso ed esige attenzione e apprendimento continui: cercare e saper riconoscere chi e cosa, in mezzo all\'inferno, non è inferno, e farlo durare, e dargli spazio. (Italo Calvino)",
		"Spesso una cosa stupida si regge perché viene approvata dalla Legge. (Trilussa)",
		"Quanto più l\'uomo capisce la vita, tanto più deve amare gli uomini, nonostante tutto. (Pär Fabian Lagerkvist)",
		"Sono le difficoltà a mostrare gli uomini. (Epitteto)",
		"Preferisco essere odiato per ciò che sono, piuttosto che essere amato per ciò che non sono. (Kurt Cobain)",
		"Le menti sono come i paracadute: funzionano solo quando sono aperte. (attribuita a Thomas Dewar)",
		"Se v\'è per l\'umanità una speranza di salvezza e di aiuto, questo aiuto non potrà venire che dal bambino, perché in lui si costruisce l\'uomo. (Maria Montessori)",
		"Ora tutto appare chiaro alla generazione che passa, e si meraviglia degli errori, ride della semplicità dei suoi antenati, e non vede che un fuoco celeste irradia tutti questi annali, che grida da essi ogni lettera, e che di là, penetrante, un dito s\'appunta proprio su essa, su essa, la generazione che passa. Ma ride la generazione che passa, e sicura di sé, orgogliosa, dà inizio a una nuova serie di errori, sui quali a loro volta rideranno i posteri. (Nikolaj Vasil\'evič Gogol\')",
		"Ti odierò, se potrò; altrimenti ti amerò mio malgrado. (Publio Ovidio Nasone)",
		"Più l\'uomo sa e più perdona. (Caterina II di Russia)",
		"Non capite, se giudicate. (Lev Tolstoj)",
		"Io non preferirei né l\'uno né l\'altro; ma, se fosse necessario o commettere ingiustizia o subirla, sceglierei il subire ingiustizia piuttosto che il commetterla. (Platone, attribuita a Socrate)",
		"La cortesia è la medicina delle donne, la cortesia è il massimo ornamento; bellezza senza cortesia è come un giardino senza fiori. (Aśvaghoṣa)",
		"Io stesso allora non dubitavo che in qualunque momento chiunque di noi, uomo, donna, bambino, forse anche il povero ronzino legato alla ruota del mulino, chiunque sapesse cosa era giusto. Tutte le creature vengono al mondo con dentro la memoria della giustizia. (John Maxwell Coetzee)",
		"La vera cultura è mettere radici e sradicarsi. Mettere radici nel più profondo della terra natia. Nella sua eredità spirituale. Ma è anche sradicarsi e cioè aprirsi alla pioggia e al sole, ai fecondi apporti delle civiltà straniere... (Léopold Sédar Senghor)",
		"La vecchiaia ama sempre la veglia; quasi che l\'uomo, quanto più lungo è il tempo che l\'ha tenuto allacciato alla vita, tanto di meno abbia a che fare con ciò che rammenta la morte. (Herman Melville)",
		"I giovani non sono vasi da riempire ma fiaccole da accendere. (Plutarco)",
		"È curioso a vedere, che gli uomini di molto merito hanno sempre le maniere semplici, e che sempre le maniere semplici sono prese per indizio di poco merito. (Giacomo Leopardi)",
		"Un uomo chiamato a fare lo spazzino dovrebbe spazzare le strade così come Michelangelo dipingeva, o Beethoven componeva, o Leontyne Price cantava al Metropolitan Opera, o Shakespeare scriveva poesie. Egli dovrebbe spazzare le strade così bene al punto che tutti gli ospiti del cielo e della terra si fermerebbero per dire che qui ha vissuto un grande spazzino che faceva bene il suo lavoro. (Martin Luther King)",
		"Se anche parlassi le lingue degli uomini e degli angeli, ma non avessi la carità, sono come un bronzo che risuona o un cembalo che tintinna. E se avessi il dono della profezia e conoscessi tutti i misteri e tutta la scienza, e possedessi la pienezza della fede così da trasportare le montagne, ma non avessi la carità, non sono nulla. (Paolo di Tarso)",
		"Tutte le cose eccellenti sono tanto difficili quanto rare. (Baruch Spinoza, Ethica)",
		"Oh, Vento, se viene l\'Inverno, potrà la Primavera essere lontana? (Percy Bysshe Shelley)",
		"L\'arte dello scrivere consiste nel ripetere cose già dette e nel ripeterle in modo che la gente creda di leggerle per la prima volta. (Remy de Gourmont)",
		"Crea tutta la felicità che sei in grado di creare, elimina tutta l\'infelicità che sei in grado di eliminare: ogni giorno ti darà l\'occasione, ti inviterà ad aggiungere qualcosa ai piaceri altrui, o a diminuire qualcosa delle loro sofferenze. (Jeremy Bentham)",
		"Inverno. Come un seme il mio animo ha bisogno del lavoro nascosto di questa stagione. (Giuseppe Ungaretti)",
		"Il bambino è padre dell\'uomo, e vorrei che la devozione alla Natura legasse i miei giorni l\'uno all\'altro. (William Wordsworth)",
		"È meglio dare che ricevere, ma a volte c\'è più umiltà nell\'accettare piuttosto che nel dare. (Søren Kierkegaard)",
		"O neve natalizia di Betlemme cadi soavemente in morbide falde, e semina il grano che deve germinare nei campi dell\'eternità. Fa\' cadere in silenzio candidi semi nei cuori oscuri e freddi intirizziti dal freddo della notte. (Johannes Jørgensen)",
		"V\'è un solo eroismo al mondo: vedere il mondo com\'è e amarlo. (Romain Rolland)",
		"Chi disputa allegando l\'autorità, non adopra lo \'ngegno, ma più tosto la memoria. (Leonardo da Vinci)",
		"Se il destino è contro di noi, peggio per lui. (1 Reggimento carabinieri paracadutisti \"Tuscania\")",
		"Mantieni ad ogni costo una mente aperta, ma non così aperta che il tuo cervello caschi fuori. (proverbio inglese)",
		"La responsabilità è ciò che attende fuori dell\'Eden della creatività. (Nadine Gordimer)",
		"Ciò che diciamo principio spesso è la fine, e finire è cominciare. La fine è là onde partiamo. (Thomas Stearns Eliot)"
	));
}
