package techbrain.wikibot.utils;

import android.widget.ArrayAdapter;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import techbrain.wikibot.RetrieveNonciclopediaTask;

public class WikiConstants {

	static String WIKI_PREFIX = "https://it.wikipedia.org/wiki/";
	public static String NONCICLOPEDIA_URL = "http://nonciclopedia.wikia.com/wiki/Speciale:PaginaCasuale";

	public static String CX = "004001173590099652672:ls07lv3jtwm";
	public static String GAK = "AIzaSyCf8GaliX65nWeelUq5so0dg5H14sYFv3c";

	static ArrayList<String> wikipediaItems = new ArrayList<String>(Arrays.asList(
		"Moto perpetuo",
		"Ragogna",
		"Oro di Yamashita",
        "Fenomeno delle voci elettroniche",
        "Rimozione chirurgica della fistola anale di Luigi XIV",
        "Swaffelen",
        "Atuk",
        "Azzurrina",
        "Illusione uditiva",
        "Riflessologia (medicina alternativa)",
        "Junk science",
        "Lottologia",
		"Versoaln",
		"Numero socievole",
		"Personaggio tipo",
		"Progesterex",
		"Decrescita",
		"Lancio di vipere da elicotteri",
		"Fantastiliardo",
		"Servetta trace",
		"Prima donne e bambini",
		"Mirmecofilia",
		"Zombie",
		"Morgellons",
		"Kodama (spirito)",
		"Problema dei filosofi a cena",
		"Fenomeno celeste di Norimberga",
		"Gamba de legn",
		"Sindrome della mano aliena",
		"Incidente del passo Djatlov",
		"Rospodotto",
		"Mars One",
		"Matto dell\'imbecille",
		"Glass House",
		"DeLorean (macchina del tempo)",
		"Bibbia Poliglotta di Walton",
		"Asparagi di Rommel",
		"St. Paul\'s Survives",
		"Reframing",
		"Palmanova",
		"Giovanni Battista Lulli",
		"Disastro di Monongah",
		"Trattamenti alternativi contro il cancro",
		"Pensare all\'immortalità del granchio",
		"Teoria della melanina",
		"Simbolo della pace",
		"Esecuzione postuma",
		"Confusione e diffusione",
		"Apparecchiature incamiciate",
		"Tapis roulant cosmico",
		"Elizabeth Odio Benito",
		"Labirinto a bracci radiali",
		"Campo di distorsione della realtà",
		"Custode della genesi",
		"!!!",
		"Ingegner Cane",
		"Data di nascita di Gesù",
		"Maledizione del Colonnello",
		"Elena Lucrezia Cornaro",
		"Sfere metalliche di Klerksdorp",
		"Idillio di Sigfrido",
		"La tomba perduta di Gesù",
		"La fabbrica del terrore",
		"Palla eh!",
		"Santo prepuzio",
		"Teatro di verzura",
		"Copyleft",
		"Inter",
		"Scienza di confine",
		"Grotta Verde",
		"Senegambia",
		"Chiesa di San Giacomo a Scossacavalli",
		"Grolla",
		"Preparato 500",
		"Teorie del complotto su Jonestown",
		"Phoneutria nigriventer",
		"Antievoluzionismo",
		"Il poeta mangiatore di leoni nel covo di pietra",
		"Dose equivalente a una banana",
		"Scopatori Segreti",
		"Ho visto cose che voi umani",
		"London Transport Museum",
		"Polvere di simpatia",
		"Zar (carro armato)",
		"Voyager Golden Record",
		"Campane dell\'arcidiocesi di Milano",
		"Bikini metallico della principessa Leila",
		"Gioiello di Vicenza",
		"Meditazione trascendentale",
		"Eudosso di Cizico",
		"Tribù dal Cuore Cornuto",
		"Mary had a little lamb",
		"La risposta alla domanda fondamentale sulla vita, l\'universo e tutto quanto",
		"1 Night in Paris",
		"Music for Supermarkets",
		"Autostrada dei Laghi",
		"Difesa Chewbacca",
		"Brethariano",
		"Criptozoologia",
		"Ummo",
		"Portale (immaginario)",
		"Mare della Pečora",
		"Ucronia",
		"Reprua",
		"Tizio, Caio e Sempronio",
		"Arturo Osio (banchiere)",
		"Halobates",
		"Brigitta Bulgari",
		"Preadamiti",
		"Corona imperiale di stato",
		"Reperti archeologici della metropolitana di Napoli",
		"Phineas Gage",
		"Eviternità",
		"Jonestown (Guyana)",
		"Triangolo delle Bermude",
		"Rasoio di Hanlon",
		"Foresta ubriaca",
		"Controilluminazione",
		"Magazzini del governo",
		"Spaghetti code",
		"Grotta di Altamira",
		"Segnale Wow!",
		"Teorie del complotto sull\'attentato al Pentagono dell\'11 settembre 2001",
		"Scacchi esagonali",
		"Elenco analitico dei cornuti",
		"Sezione aurea",
		"Bombardamento di Bari",
		"Via Vittorio Emanuele III",
		"Grande puzza",
		"Storia culturale dei glutei",
		"Puff, the Magic Dragon",
		"Balabiótt",
		"Sindrome locked-in",
		"International Cometary Explorer",
		"Chief Mouser to the Cabinet Office",
		"Death café",
		"Culoz",
		"2+2=5",
		"Pigasus Award",
		"Nepenthes bicalcarata",
		"Fuoco di Sant\'Elmo",
		"Caccola",
		"Raggio della morte",
		"Concilio in Trullo",
		"Coppa di Licurgo",
		"Lettura del biglietto",
		"Enciclopedia Galattica",
		"IP over Avian Carriers",
		"Reductio ad Hitlerum",
		"Nuova cronologia",
		"Realismo isterico",
		"Gotto Esplosivo Pangalattico",
		"Monte Loffa",
		"Teorie del complotto sul riscaldamento globale",
		"Puzzone di Moena",
		"Black Holes and Time Warps",
		"Fonte Q",
		"Gloomy Sunday",
		"Malato di calcio",
		"Mirin Dajo",
		"Dodecateismo",
		"Giro di Viso",
		"Finta guerra",
		"Stazioni dell\'arte",
		"Leggende metropolitane giapponesi",
		"Pallio di San Lorenzo",
		"Cravatta di Sherman",
		"Savignano a Mare",
		"Piazza della Passera",
		"Aokigahara",
		"Scaled Composites SpaceShipTwo",
		"Geobiologia",
		"Articoli nei quali si passano in rassegna gli abusi che sono stati corretti",
		"Nibiru (Sitchin)",
		"Fortean Society",
		"Bacio della pantofola",
		"Epitaffio di Sicilo",
		"Clamoroso al Cibali!",
		"49 Pales",
		"Pyrococcus furiosus",
		"Giovanni Aldini",
		"Euthanasia Coaster",
		"Teschio di cristallo",
		"Composto di gas nobili",
		"Ciarlatano",
		"Massacro della Zong",
		"Casa Scaccabarozzi",
		"Kilroy",
		"Labirinto di Porsenna",
		"RTFM",
		"Castello di Guédelon",
		"Brainfuck",
		"Parco degli Acquedotti",
		"Teomondo Scrofalo",
		"Bibliopegia antropodermica",
		"Q33 NY",
		"Luci Yehudi",
		"Arsenal Firearms AF2011A1",
		"Locomotiva C&O M-1",
		"Ordine dei byte",
		"Trimetilarsina",
		"Disastro di Marcinelle",
		"Secondo intercalare",
		"Foca (imperatore)",
		"2 Pallas",
		"Clavicembalo elettrico",
		"Cronometro di Loulié",
		"El Corte Inglés",
		"Glocalizzazione editoriale",
		"Ansible",
		"Hashima (isola)",
		"Generale Sherman",
		"Matcha",
		"Raising the Flag on Iwo Jima",
		"Árpád Weisz",
		"Arbegnuoc",
		"Flakturm",
		"Kim Peek",
		"Teoria delle finestre rotte",
		"Storia della Geromina",
		"Persocom",
		"Agricoltura biodinamica",
		"Api anti-bomba",
		"There Is No Alternative",
		"Mawangdui",
		"Scacchi tridimensionali",
		"Teorema della pizza",
		"Esame del carbonio 14 sulla Sindone",
		"Idillio infranto",
		"Lukla",
		"Cartellate",
		"Arduino (hardware)",
		"Gorsafawddacha\'idraigodanheddogleddollônpenrhynareurdraethceredigion",
		"Carta igienica",
		"Centrale termoelettrica di Trbovlje",
		"Bananadina",
		"OOPArt",
		"Maso chiuso",
		"Ferrovia_sospesa",
		"Nanotecnologia nella fantascienza",
		"Nella vecchia fattoria",
		"Metodo del tubo di gomma",
		"Trasferimento della mente",
		"Antenna radio di Varsavia",
		"Santuario di Itsukushima",
		"Scienziato pazzo",
		"Coral Castle",
		"La persecuzione e l\'assassinio di Jean-Paul Marat, rappresentato dalla compagnia filodrammatica dell\'ospizio di Charenton sotto la guida del marchese de Sade",
		"Progetto Montauk",
		"Emirates Air Line (cabinovia)",
		"Harukichi Shimoi",
		"Premio Ig Nobel",
		"Robots.txt",
		"Ferrofluido",
		"Viaggio nel tempo",
		"Cucchiaino nello spumante",
		"Volta (danza)",
		"Museo fallologico islandese",
		"Cifrario di Cesare",
		"durian",
		"Gun (lampada)",
		"Cappella di San Luigi a Capezzolo",
		"Salto di Tiberio",
		"Honorificabilitudinitatibus",
		"Impronte degli dei",
		"Escursione someggiata",
		"Schmallenberg virus",
        "Fenomeno da baraccone",
		"Giochi inaugurali dell\'anfiteatro Flavio",
		"Dornier Do 335",
		"Patafisica",
		"Neko café",
		"Spedizione Donner",
		"Castellana di Vergi",
		"Orgone",
		"Nasser Al-Attiyah",
		"Linee temporanee",
		"Casa Fenoglio-Lafleur",
		"Hermetia illucens",
		"Uomo Assorbente",
		"Cronologia del futuro lontano",
		"Rabdomanzia",
		"Memoria dell\'acqua",
		"Impero aericano",
		"Feng shui",
		"All your base are belong to us",
		"Starchild",
		"Eruzione Coca-Cola Light e Mentos",
		"Dominio del mondo",
		"Ippogallo",
		"Piaggio Vespa 150 TAP",
		"Troll (internet)",
		"Porta dell\'inferno",
		"Disastro del Maracanã",
		"Motore magnetico Perendev",
		"Deinococcus radiodurans",
		"Baciatico",
		"Fantasma Formaggino",
		"Scrittura corsiva romana",
		"Eppur si muove",
		"Evento di Tunguska",
		"The Hands Resist Him",
		"Lupo mangia-frutta",
		"Felicità interna lorda",
		"Dama bianca (spirito)",
		"Fallen Astronaut",
		"Ipotesi alternative sull\'AIDS",
		"MT e MN",
		"Hemp Body Car",
		"Mummia di palude",
		"Piccione fotografo",
		"Afsluitdijk",
		"Teorie alternative sulla morte di Napoleone Bonaparte",
		"Gioco del cento",
		"Mu (continente)",
		"Lohengrin (opera)",
		"Quadrato_del_Sator",
		"Galassie Antenne",
		"Acquacheta",
		"Veicolo spaziale Sojuz",
		"Freedom House",
		"Forza Odica",
		"Tuta distillante",
		"Kuchisake-onna",
		"Processo zombie",
		"Bibbia Cattiva",
		"Pompone",
		"Pianeta oceano",
		"Eurabia",
		"High Frequency Active Auroral Research Program",
		"Artemisia I",
		"Numero primo illegale",
		"Teiera di Russell",
		"Wilhelm von Gloeden",
		"Nonno di Panopoli",
		"Ernesto Teodoro Moneta",
		"Han Shot First",
		"Censura nella Repubblica Democratica Tedesca",
		"Sony timer",
		"Cappello di carta stagnola",
		"Merda d\'artista",
		"UFO nazisti",
		"Black Ivory",
		"Leonarda Cianciulli",
		"Pierre Virion",
		"Tesoro dell\'Esquilino",
		"Cristiano Augusto di Schleswig-Holstein-Sonderburg-Augustenburg (1768-1810)",
		"Viaggiatori extratemporali",
		"Disco protoplanetario",
		"Ibrido grizzly-orso polare",
		"Hello world",
		"Lista di avvistamenti UFO",
		"Teoria del complotto",
		"Lista di gadget nei film di James Bond",
		"Strada delle 52 gallerie",
		"Metamodello",
		"Llanhyfryddawelllehynafolybarcudprindanfygythiadtrienusyrhafnauole",
		"The Beatles",
		"Pericolo giallo",
		"Benjaman Kyle",
		"Guerra del calcio",
		"Osculum infame",
		"Effetto Pauli",
		"Il Dio fumoso",
		"Pianeta di carbonio",
		"Erettore del pelo",
		"Alto tedesco medio",
		"Nakagin Capsule Tower",
		"Chupacabra",
		"Teoria del complotto sulle scie chimiche",
		"Irredentismo italiano a Nizza",
		"Marcello Truzzi",
		"Discordianesimo",
		"Frenologia",
		"Debunker",
		"The Boy Bands Have Won",
		"Occulto",
		"Guerra di Corea",
		"Affare XYZ",
		"Difficile lectu",
		"Hibernia ed Impero Romano",
		"Darwin Awards",
		"Cryptex",
		"Pelo libero",
		"Teorie del complotto sul signoraggio",
		"Paradosso del nonno",
		"Grotta Son Doong",
		"Zecche scozzesi",
		"Cacatio matutina est tamquam medicina",
		"John Taylor",
		"Powers That Be",
		"Iscrizione di Pilato",
		"Bicicletta in bambù",
		"Robert la Bambola",
		"Promontorio dell\'Argentario",
		"Detto, fatto!",
		"Fiocco di neve di Koch",
		"Legge di Jante",
		"Programmazione neuro linguistica",
		"Portsmouth Sinfonia",
		"Rongorongo",
		"Aka manto",
		"Horace Wells",
		"Cose che nessuno sa",
		"Piedino (sessualità)",
		"Scitala",
		"Erich Hartmann",
		"Aeroplanino di carta",
		"Colonizzazione italiana delle Americhe",
		"Mercurio rosso",
		"Spostamento verso il rosso",
		"Scomunica ai comunisti",
		"Nemesis",
		"Effetto Tetris",
		"Congettura di protezione cronologica",
		"Fucking",
		"Italia-Francia (1910)",
		"Magia",
		"Piazza Umberto I (Capri)",
		"Holocron",
		"Burning Man",
		"Linea di sangue di Gesù",
		"NF-Board",
		"Lucio Anneo Cornuto",
		"Il mistero del Sacro Graal",
		"Massa critica (ciclismo)",
		"Spoonerismo",
		"Lampadina centenaria",
		"Legge di Murphy",
		"Roberto Oros di Bartini",
		"Maledizione delle risorse",
		"Isola dei Fagiani",
		"Facite ammuina",
		"Leonid Rogozov",
		"Fuoco greco",
		"Code talker",
		"Cher Ami",
		"Eclissi solare del 20 marzo 2015",
		"Tarzanide",
		"Tex Winter",
		"Tong zi dan",
		"Fattoria dei corpi",
		"Risposta alla domanda fondamentale sulla vita, l\'universo e tutto quanto",
		"Bomba atomica da zaino",
		"Jenny Haniver",
		"Abito del medico della peste",
		"Hetalia Axis Powers",
		"Linguaggio degli SMS",
		"Aeroporto di Courchevel",
		"Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo",
		"Ostrichetrancidipescesalatocagnoligattuccipezzidicefaloinsalsapiccantesilfiooliomieletordimerlicolombaccicolombellegallettilodolearrostocutrettolepiccioniselvaticilepricottenelvinocroccanticantuccini",
		"Storia della frontiera sul Monte Bianco",
		"Sorpresa!",
		"Shoefiti",
		"Peter Iredale",
		"Olympias",
		"Parelio",
		"Flat Earth Society",
		"Pseudostoria",
		"La Zisa",
		"Macchina di Anticitera",
		"Bordello del campo di concentramento",
		"Teoria di Olduvai",
		"Mitologia Gong",
		"Progetto Habakkuk",
		"Repubblica rossa di Caulonia",
		"I nove sconosciuti",
		"Babbo Natale",
		"Kakka",
		"Tudor City",
		"Tassa kosher",
		"Cimatica",
		"Mary Shelley",
		"Saggio alla fiamma",
		"Banana blu",
		"Frattura del pene",
		"Saint Kilda",
		"Convegno dell\'hotel Parco dei Principi",
		"Castello di Brissac",
		"Licantropo",
		"Anteo Zamboni",
		"Messaggio di Arecibo",
		"Cimitero monumentale di Messina",
		"Fnord",
		"Wolbachia",
		"Calibro 89",
		"Sepoltura da vivo",
		"Polpo Paul",
		"Stazioni fantasma della metropolitana di Berlino",
		"Congetture del 1421 e del 1434",
		"Cronovela",
		"Confine tra il Regno Unito e la Spagna",
		"Bordighera",
		"Teoria ingenua degli insiemi",
		"Allghoi Khorhoi",
		"Le Superchicche",
		"Raggio traente",
		"Quasigruppo",
		"Bohemian Grove",
		"Denominazioni alleate dei velivoli giapponesi",
		"Cooping",
		"Rocco Petrone",
		"Locomotiva Bayard",
		"Letters of last resort",
		"Tacchino induttivista",
		"Hughes H-4 Hercules",
		"chitarra acustica",
		"Kitsune no Yomeiri",
		"Dodo",
		"Aginter Press",
		"Giorgio Napolitano",
		"Bradley Manning",
		"Passera scopaiola",
		"Bufo bufo",
		"Assiani (soldati mercenari)",
		"Magic Roundabout",
		"Oggetti non stellari nella costellazione di Cassiopea",
		"Macchina dei Miracoli",
		"Jack Churchill",
		"Ho ho ho",
		"Cappella Sansevero",
		"Genocidio armeno",
		"Cane Nero magna bella persica",
		"Sfruttamento del 10% del cervello",
		"Scatola Madre",
		"Operazione Chaos",
		"Tesoro di Hoxne",
		"Polybius (videogioco)",
		"Abbracci gratis",
		"James while John had had had had had had had had had had had a better effect on the teacher",
		"Uncanny valley",
		"Hueyatlaco",
		"Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu",
		"Esperimento di Filadelfia",
		"Big Hole",
		"Gruppo Rondoi-Baranci",
		"Cesare Lombroso",
		"Oggetto sottomarino non identificato",
		"Mutuno Tutuno",
		"Cartello Phoebus",
		"31 febbraio",
		"Fernando Leoni",
		"Tonoscopio",
		"Unità 731",
		"De situ Britanniae",
		"Teorie del complotto sulla SARS",
		"Elefante della Bastiglia",
		"Postumo (Lucio Battisti)",
		"Buco di Viso",
		"Rapporto La Guardia",
		"Movimento per l\'estinzione umana volontaria",
		"Ipotesi del tempo fantasma",
		"Potešnye vojska",
		"Futuro della Terra",
		"Abuso rituale satanico",
		"Tregua di Natale",
		"Pietro Camedda",
		"Tuttomondo",
		"Monowi",
		"Specchio (immaginario)",
		"Operazione Tannenbaum",
		"Ordine del Bagno",
		"Sceblasti",
		"Violino a bastone",
		"Virgola mobile",
		"Incidente stradale di Bridget Driscoll",
		"Munaciello",
		"Maledizione di Superman",
		"Longplayer",
		"Uccello di Saqqara",
		"Labirinto di Barnes",
		"La Luisona",
		"Curva spaziotemporale chiusa di tipo tempo",
		"Gerbilling",
		"Numeri pseudo-casuali",
		"Chrysler Norseman",
		"Tailleur rosa Chanel di Jacqueline Bouvier Kennedy",
		"Teatro della Concordia (Monte Castello di Vibio)",
		"Canal du Midi",
		"Scala per pesci",
		"Giovanni Gasti",
		"Motoruota",
		"The First Team",
		"Paradosso temporale",
		"Sergio Scaglietti",
		"Die Glocke",
		"Operazione Ruthless",
		"Crinoidea",
		"Turritopsis nutricula",
		"Papiro Edwin Smith",
		"Hégésippe Simon",
		"Caso Taman Shud",
		"Ragni fritti",
		"Willis Tower",
		"Elisabeth Freeman",
		"Fortezze marittime Maunsell",
		"Federazione Ginnastica d\'Italia",
		"The quick brown fox jumps over the lazy dog",
		"Fiori di Bach",
		"Italiana 5 birilli",
		"Neocreazionismo",
		"Avventura testuale",
		"Locomotiva DB 184",
		"Fattoide",
		"Quarto Reich",
		"Dagen H",
		"Solomon Northup",
		"Ascensore spaziale",
		"Georgia Guidestones",
		"Kepler-64 b",
		"Buco della memoria",
		"Mano della Gloria",
		"Guerra degli emù",
		"Violino piccolo",
		"Accordo di tredicesima",
		"Fred Ott\'s Sneeze",
		"Organ²/ASLSP",
		"L\'arcobaleno",
		"Teoria del complotto del Nuovo ordine mondiale",
		"Pranoterapia",
		"Premio Oscar",
		"Rivarossi",
		"Schiacciamento da elefante",
		"Unione degli Atei e degli Agnostici Razionalisti",
		"Pietra runica di Kensington",
		"Charles Fort",
		"Materia strana",
		"d3o",
		"69º Gran Premio Indianopolis",
		"Alimentazione medievale",
		"Aerodrome A",
		"USS Arizona (BB-39)",
		"Flibbiddydibbiddydob",
		"Teoria degli antichi astronauti",
		"Magia bianca",
		"RealDoll",
		"Pierino (barzellette)",
		"Messaggio subliminale",
		"Zercone",
		"Gol fantasma",
		"Nautilus (Verne)",
		"Manifesto della cucina futurista",
		"Macchina dei sogni",
		"Serafino (tifoso)",
		"The Skeptic\'s Dictionary",
		"Matrice del comando",
		"Idrocolonterapia",
		"Bestiarius",
		"Mayday",
		"Il cancro è un fungo",
		"Raid di Tondern",
		"Pollice verso",
		"Milizia Tradizionale di Calasca",
		"Guerrillero Heroico",
		"Limite K-T",
		"Viola organista",
		"Serie UP",
		"Associazione Calcio Perugia 1978-1979",
		"Eterocromia",
		"Ruota degli esposti",
		"Teoria del pazzo",
		"Guerra anglo-zanzibariana",
		"Colonizzazione curlandese delle Americhe",
		"Morbo di Pompe",
		"Patriottismo insetticida",
		"Lettera di Bixby",
		"Uomo selvatico",
		"Tal der Ahnungslosen",
		"Sistema ticonico",
		"Lonesome George",
		"Maledizione del Bambino",
		"Aura (medicina)",
		"Nuraghe",
		"Razza ariana",
		"Alieni nordici",
		"Morris Jessup",
		"Quasi-guerra",
		"London Beer Flood",
		"Didi Senft",
		"Cervellato",
		"Iridologia",
		"Pegaso (mitologia)",
		"Morte di Diana Spencer",
		"Eva Klotz",
		"Bull-baiting",
		"Amuleto",
		"Sassi di Matera",
		"Pietro Conti (1796-1856)",
		"Labirinto della Masone",
		"Fiat Multipla (1998)",
		"Bruce Lipton",
		"Corvi della Torre di Londra",
		"Psiconeuroendocrinoimmunologia",
		"Casalinga di Voghera",
		"Rrröööaaarrr",
		"Spigolamento abusivo",
		"Gigante di Cardiff",
		"Re Davide (leggenda)",
		"Studio sulla sifilide di Tuskegee",
		"Lista_dei_più_grandi_pezzi_di_artiglieria_per_calibro",
		"Ronald Mallett",
		"Girolamo Ortis",
		"Equus quagga quagga",
		"Teorema spettrale",
		"Autoalveare",
		"Gulo gulo",
		"L\'arrivo di un treno alla stazione di La Ciotat",
		"Pino sulla Sponda del Lago Maggiore",
		"Provincia di Batman",
		"Botte volante",
		"Protocolli dei Savi di Sion",
		"Ed Alonzo",
		"Cultura dei telefoni cellulari in Giappone",
		"Invisibile Unicorno Rosa",
		"Canto delle dame",
		"Ripetizione dilazionata",
		"Catenano",
		"Bentley State Limousine",
		"Destino ultimo dell\'universo",
		"Fate di Cottingley",
		"Giapeto",
		"Nido di rondine",
		"Drapetomania",
		"Cane cinese Chongqing",
		"Bomba Zar",
		"Bardenas Reales",
		"Operazione Chastise",
		"Christopher McCandless",
		"Leggenda della morte di Paul McCartney",
		"Surf sulla folla",
		"Museo delle anime del Purgatorio",
		"Mark Boyle",
		"Stemma di Siena",
		"Ma con gran pena le reca giù",
		"Cinisca",
		"Corpo grottesco",
		"Bandiera terrestre",
		"Australia-Samoa Americane 31-0",
		"Santo Prepuzio",
		"Controversia di Praga",
		"Cappellone degli Spagnoli",
		"Macchia fredda nella radiazione cosmica di fondo",
		"TARDIS",
		"Sudicio Rinverdito",
		"Glicone",
		"Fine del mondo",
		"Punto di Feynman",
		"Cospirazione della General Motors",
		"Leggenda nera dell\'Inquisizione",
		"Grande Macchia Rossa",
		"Digivice",
		"Petalismo",
		"Cacopedia",
		"Porta Alchemica",
		"Negazionismo dell\'Olocausto",
		"Principato di Sealand",
		"NESARA",
		"CHE/COSA/TE/NE/FAI/DI/UN/TITOLO",
		"Les Fastes de la grande et ancienne Mxnxstrxndxsx",
		"Ciòunglobulo Blu",
		"Gata Carogna",
		"Gödel, Escher, Bach: un\'eterna ghirlanda brillante",
		"Ancoraggio (PNL)",
		"Architettura di un processore basato su registri generali",
		"Alice Prin",
		"Autoleone",
		"Stati per consumo di birra pro capite",
		"Kolinahr",
		"Blakennomion",
		"Gallerie del monte Soratte",
		"Stadium",
		"Moto di puro rotolamento",
		"Emerenzia",
		"Optofono",
		"Penis captivus",
		"Aelia Laelia Crispis",
		"Technobabble",
		"I cancelli del cielo",
		"Museum of Bad Art",
		"Specie aliena",
		"Craniopagus parasiticus",
		"Vincenzo Tiberio",
		"Vuvuzela",
		"Kalakukko",
		"Cioccolato delle forze armate statunitensi",
		"Orologio dell\'apocalisse",
		"Porta del Tempo",
		"Varietà invariante",
		"Toilette in Giappone",
		"Archeologia misteriosa",
		"Beffa del monossido di diidrogeno",
		"Piede da trincea",
		"Nottolino browniano",
		"Irukandji",
		"Pionieri mormoni con carretto a mano",
		"Ferrovia della Jungfrau",
		"Roar (nome)",
		"Rolfing",
		"Cosmonauti perduti",
		"Coppa del mondo VIVA",
		"Isola Budelli",
		"Ambystoma mexicanum",
		"Labirinto di Cnosso",
		"Uovo con gallina",
		"Profezie sul 21 dicembre 2012",
		"Sindrome di Parigi",
		"Adam Kadmon (personaggio)",
		"Legione dei Superanimali",
		"Carlo Urbani",
		"Teoria del complotto sull\'attacco di Pearl Harbor",
		"Monte Testaccio",
		"Pizzaiolo acrobatico",
		"Boeing X-43",
		"Volo Aeroflot 593",
		"2012 DA14",
		"Villa Mocenigo (Marocco)",
		"RoboCup",
		"Ilse Koch",
		"Laboratorio di Zetetica",
		"Interzato in grembo appuntato",
		"Cleptocrazia",
		"Friendly Floatees",
		"Ipotesi sull\'elezione papale di Giuseppe Siri",
		"Diamante del fabbricante di cucchiai",
		"Chiasmodon niger",
		"Dita a V",
		"Malarioterapia",
		"La prigione (opera teatrale)",
		"Hexakosioihexekontahexafobia",
		"Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch",
		"Fantawestern",
		"Satelliti naturali di Marte",
		"Città di transizione",
		"Borghi putridi",
		"Derweze",
		"Stronzate. Un saggio filosofico",
		"Jack il saltatore",
		"Cross (album)",
		"Effetto Holtzman",
		"Pianoforte a gatti",
		"Getto blu",
		"Lingua della suocera",
		"Paradosso del mentitore",
		"Meretrix",
		"Piramidologia",
		"Sindrome di Fregoli",
		"Antigravità",
		"Idroscalo di Torino",
		"Viaggio immaginario",
		"Cropsey",
		"Sbarramento Pian dei Morti",
		"La nave e il faro (leggenda metropolitana)",
		"Jon Frum",
		"Watch the K Foundation Burn a Million Quid",
		"Vergine di Norimberga",
		"Pioggia di animali",
		"L\'opera da tre soldi",
		"Donaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaft",
		"Corpus Clock",
		"Toussaint Louverture",
		"...4..3..2..1...morte",
		"Bella \'mbriana",
		"Vaso di Dorchester",
		"Traduttore universale",
		"Criosollevamento",
		"Sismoscopio di Zhang Heng",
		"Raimondo di Sangro",
		"Boomdotto",
		"Razzie Award alla peggior sceneggiatura",
		"Monastero di Santa Caterina (Egitto)",
		"Paradosso della predestinazione",
		"Scazzamurrieddhru",
		"Mil Mi-12",
		"Il naufragio del Titan",
		"Emicrania da gelato",
		"Agloe",
		"Eric Moussambani",
		"Uomo falena",
		"Chicken tikka masala",
		"Bullshit!",
		"Pioggia rossa in Kerala",
		"Globus Cassus",
		"Calendario sexy",
		"Lingua artificiale",
		"Satellite KEO",
		"Clinica Burzynski",
		"Genio del male",
		"Armonica a bicchieri",
		"Riordino dei musei del Castello Sforzesco",
		"SS Schenectady",
		"Cervello positronico",
		"Sacrario militare di Redipuglia",
		"Domenico Mastini",
		"Teoria del complotto lunare",
		"Tafazzi",
		"Servizio P",
		"Gropecunt Lane",
		"Pascalina",
		"Piaggio Vespa",
		"Fontana delle tette",
		"Abraham de Moivre",
		"Buonadonna",
		"Noetica (pseudoscienza)",
		"Acámbaro",
		"Affinità-divergenze fra il compagno Togliatti e noi - Del conseguimento della maggiore età",
		"Per Euxenippo",
		"Labirinto acquatico di Morris",
		"Albero del Ténéré",
		"Principio di autoconsistenza di Novikov",
		"Strada guidata",
		"Yonaguni",
		"Bo (nome)",
		"Leo Pardi",
		"Interpretazione a molti mondi",
		"Inugami",
		"Respirazione olotropica",
		"Moltiplicatore monetario",
		"Altrove (fumetto)",
		"Aeroporto di Lukla",
		"Carrozza_Centoporte",
		"Paga quello che vuoi",
		"Prescienza",
		"Club 27",
		"Pietre di Ica",
		"Contessina Selvaggia Serbelloni Mazzanti Viendalmare",
		"Linda Burfield Hazzard",
		"Mona (nome)",
		"Canguro fantasma",
		"Lago di Ha! Ha!",
		"Lingerie Football League",
		"Morte da ventilatore",
		"Da Atlantide alla Sfinge",
		"Ponte di Einstein-Rosen",
		"30 febbraio",
		"Effetto Leidenfrost",
		"Architettura eoliana",
		"Spada dell\'Islam",
		"274301 Wikipedia",
		"Sinarchia",
		"Miracolo eucaristico di Lanciano",
		"Frontiera dei portafogli",
		"Cimitero delle 366 Fosse",
		"Baldwin Street",
		"Guerra dei trecentotrentacinque anni",
		"Ittioterapia",
		"Scemo del villaggio",
		"Fotografie post mortem",
		"Antonov An-225 Mriya",
		"Googol",
		"Accoppiamento vibronico",
		"Tarrare",
		"Sperrbrecher",
		"Emmy Noether",
		"Joseph Pujol",
		"Intervista a Marco Travaglio a Satyricon",
		"Messaggio in bottiglia",
		"Procedimenti giudiziari a carico di Oscar Wilde",
		"Numero di Erdős",
		"Pianta mangia-uomini",
		"Imperial Camel Corps",
		"Edgar Cayce",
		"Labirinto di Lemno",
		"Immondo corruttore",
		"Orbitale di Banks",
		"Viola pomposa",
		"2160p",
		"Aci Trezza",
		"Manhattanhenge",
		"Arrocco Pam-Krabbé",
		"Pianeti immaginari",
		"Acciaio effervescente",
		"Margherita Teresa d\'Asburgo",
		"Great Blue Hole",
		"Pierre Plantard",
		"Time ball",
		"Kaman K-MAX",
		"Sepolcro di Matteo Ferrillo",
		"Bambini indaco",
		"Automobile a vapore",
		"Assedio di Waco",
		"2M1207 b",
		"Cerro Torre",
		"Aquila delle Scimmie",
		"Helltown",
		"Labirinto di siepi",
		"Balena 52-hertz",
		"Parco dei Mostri",
		"Fahrenheit 451",
		"Uomo dei Miracoli",
		"ISBN",
		"Nazireato",
		"William Windsor (capra)",
		"Leggenda metropolitana",
		"Supercazzora",
		"Leggenda sulle coincidenze Lincoln-Kennedy",
		"Mike il pollo senza testa",
		"Paradosso del formaggio coi buchi",
		"Batteria di Baghdad",
		"Guerra degli scimpanzé del Gombe",
		"Chiese di Chiloé",
		"Punto triplo",
		"Piaga del Ballo",
		"Passaggio per pesci",
		"Ryugyong Hotel",
		"Schwäbische Hausfrau",
		"Chesley Bonestell",
		"Segnaletica e allestimento della Metropolitana Milanese",
		"Team Hoyt",
		"Ada Lovelace",
		"Dalton Highway",
		"Sfera di Dyson",
		"Il Club Bilderberg",
		"Guardia corsa papale",
		"English as She Is Spoke",
		"Base 211",
		"Alfa Centauri Bb",
		"Vista dalla finestra a Le Gras",
		"Superleggera (sedia)",
		"Ammasso aperto",
		"Atlanta Nights",
		"Pornocrazia",
		"Pokémon shock",
		"Pseudoscienza",
		"Vestito verde Versace di Jennifer Lopez",
		"Albero di Jesse",
		"Oscar (gatto)",
		"Secondo Pollo",
		"Test di Turing",
		"Scudo deflettore",
		"Bunga bunga",
		"Elettrosensibilità",
		"Brooks Agnew",
		"Amenukal dei Kel Adagh",
		"The Vegetable Orchestra",
		"SM U-118",
		"Bubo bubo",
		"Nano cervello",
		"Oro nazista",
		"Alligatori nelle fogne",
		"Demon core",
		"Ayahuasca",
		"Carlos Castaneda",
		"Bigfoot",
		"Vadim Aleksandrovič Černobrov",
		"Vagina dentata",
		"Trotula de Ruggiero",
		"Pianeta artificiale",
		"Finocchiona",
		"Charles-André Merda",
		"Agopuntura",
		"Isole della Delusione",
		"Women Airforce Service Pilots",
		"Il santo Graal (saggio)",
		"Rotolamento di uova",
		"Effetto Kulešov",
		"Esperimento Rosenhan",
		"Dogon",
		"ICEHOTEL",
		"Bosco Verticale",
		"Sagittarius A*",
		"Piccola Scala",
		"Fluorizzazione dell\'acqua",
		"Minareto di Fasano",
		"Osservatorio astronomico Sphinx",
		"Chiesa di San Giovanni (Cerreto Sannita)",
		"Stati Uniti d\'Europa",
		"Bart Sibrel",
		"Concursante",
		"Skull and Bones",
		"Hoverboard",
		"Raid Roma-Tokyo",
		"Anno_senza_estate",
		"Football Club Internazionale Milano",
		"Allevamento di schiavi negli Stati Uniti",
		"Citrus aurantium bizzarria",
		"Cicceide",
		"Stazioni fantasma della metropolitana di Parigi",
		"Fuga geografica",
		"Misticismo quantico",
		"Caproni Ca.60 Transaereo",
		"Cavallo islandese",
		"Ponte delle Tette",
		"Principessa Mafalda",
		"Fionda gravitazionale",
		"Salto di Bidone",
		"Combattimento con le uova",
		"Rinascimento cesenate",
		"Casu marzu",
		"Concordia (Antartide)",
		"Obsolescenza programmata",
		"Up Up Up Up Up Up",
		"Bobobo-bo Bo-bobo",
		"Snopes",
		"Primo cubano",
		"Durlindana",
		"In girum imus nocte et consumimur igni",
		"Glossario delle frasi fatte",
		"Paperone de\' Paperoni",
		"Moschetto Balilla",
		"Paradosso del gatto imburrato",
		"Forme uniche della continuità nello spazio",
		"Palazzo Cheval",
		"Fiat N.3",
		"Paradosso di Achille e la tartaruga",
		"cobra di Pugačëv",
		"Museo archeologico virtuale",
		"Costanti di accoppiamento",
		"Teatro all\'italiana",
		"Dilemma del prigioniero",
		"Zuffa tra Pompeiani e Nocerini",
		"Piramidi bosniache",
		"Faro di Tiberio",
		"Stuxnet",
		"Central-Mid levels escalator",
		"Scala di Scoville",
		"Enneagramma della personalità",
		"Joshua A. Norton",
		"P♡P",
		"Sindrome respiratoria mediorientale da Coronavirus",
		"San Lucifero",
		"Siege Perilous (fumetto)",
		"Anomalia dell\'Ararat",
		"Fiat Tagliero",
		"Pila a combustibile ad acqua di Stanley Meyer",
		"Satis elucet maiorem habere vim ad discendum liberam curiositatem quam meticulosam necessitatem",
		"Battaglione sacro",
		"I segreti perduti della tecnologia nazista",
		"Canale della Mona",
		"Wikipedia:Clausola della palla di neve",
		"Sindrome di Alice nel Paese delle Meraviglie",
		"Elettrotreno FS ETR 400",
		"RRRrrrr!!!",
		"L\'uomo che sconfisse il boogie",
        "Lampade di Dendera",
		"Agnello vegetale della Tartaria",
		"Bartitsu",
		"Ecce Homo (Elías García Martínez)",
		"Bendis",
		"Monte Athos",
		"Benandanti",
		"Bücherverbrennungen",
		"Vestito di carne di Lady Gaga",
		"Controversia sulla remissione della scomunica al vescovo Richard Williamson",
		"Elefante da guerra",
		"Memoria del mondo",
		"Satellite Black Knight",
		"Tormentone estivo",
		"NIAI RK-I",
		"Terapia di conversione",
		"Charles Domery",
		"Maneki neko",
		"Paradosso del barbiere",
		"Teteun",
		"Guglielmo Braccio di Ferro",
		"Microchip (impianto umano)",
		"Miodesopsie",
		"Piezonucleare",
		"Sepoltura dei videogiochi Atari",
		"VY Canis Majoris",
		"Sol Invictus",
		"Fetus in fetu",
		"Piccola era glaciale",
		"Pastafarianesimo",
		"Tartaruga delle Galapagos",
		"Argentinosaurus huinculensis",
		"Percorso del cavallo",
		"Sci estremo",
		"Viktoria Savs",
		"Effetto Streisand",
		"Cronovisore",
		"Armiamoci e partite",
		"Hameau de la Reine",
		"NORAD Tracks Santa",
		"UVB-76",
		"Tûranor PlanetSolar",
		"Anopticon",
		"Rapport",
		"Colonna di Ferro",
		"Utero artificiale",
		"Fuente Magna",
		"Alessandra Giliani",
		"Morte di Giovanni Paolo I",
		"HD 80606 b",
		"Tubo di Krasnikov",
		"Daniel Estulin",
		"Operazione Highjump",
		"Salita in discesa",
		"Qualunquone",
		"Rinoceronte (Dürer)",
		"Teorie del complotto sull\'attentato al World Trade Center dell\'11 settembre 2001",
		"Bosco dell\'Alevé",
		"Clairvius Narcisse",
		"Tardigrada",
		"Sindrome itai-itai",
		"Bixi",
		"D\'oh!",
		"Transnistria",
		"Analogo solare",
		"Boom sonico",
		"Giufà",
		"Aron Ralston",
		"Cioccolismo",
		"St. Mary\'s (metropolitana di Londra)",
		"Chiesa di Santa Passera",
		"Bushismo",
		"Come farsi una cultura mostruosa",
		"Begich Towers Condominium",
		"Allium ascalonicum",
		"Jona 10",
		"Chemurgia",
		"Battaglioni femminili della morte",
		"Urban Legends",
		"Diritto reale di godimento",
		"Sciovinismo del carbonio",
		"Cospirazione della sorpresa d\'ottobre",
		"Sale himalayano",
		"Effetto Mozart",
		"Radioso maggio",
		"Savinien Cyrano de Bergerac",
		"La Scarzuola",
		"Gruppo Bilderberg",
		"Piramidi di Pantiacolla",
		"Geode di Coso",
		"Precipitevolissimevolmente",
		"La linea di sangue del Santo Graal",
		"Dahu",
		"Placca dei Pioneer",
		"Sorelle della Perpetua Indulgenza",
		"Porta Palatina",
		"Digosville",
		"Bioritmo",
		"Steorn",
		"Paradosso del gatto di Schrödinger",
		"Muro marocchino",
		"Monastero di Santa Caterina",
		"Dispositivo di occultamento",
		"Fontana (Duchamp)",
		"Elvis\' Greatest Shit",
		"I vitelli dei romani sono belli",
		"Eruttazione",
		"Acquedotto Carolino",
		"Temporale di neve",
		"Headington Shark",
		"Esplosione della carcassa di un cetaceo",
		"Supercalifragilistichespiralidoso",
		"Miracolina",
		"Elepoli",
		"John Titor",
		"San Guinefort",
		"Macchina che legge e che scrive",
		"Linothorax",
		"Testa di Oliver Cromwell",
		"Cacciavite sonico",
		"Regola dei cinque secondi",
		"Teoria della Terra cava",
		"HE 1523-0901",
		"Sarchiapone",
		"Arcobaleno lunare",
		"Giovanni Antonio Amedeo Plana",
		"Fabbriche di Careggine",
		"Hahaha",
		"Coleottero bombardiere",
		"Physalia physalis",
		"Una struttura di archivio, per l\'insieme, per il cambiamento e per l\'indeterminato",
		"Nido dell\'Aquila",
		"Putsch di Monaco",
		"Lingua artistica",
		"Air guitar",
		"Madonna del manganello",
		"Mary Toft",
		"Pipetta Pasteur",
		"Tromba marina (strumento musicale)",
		"Priorato di Sion",
		"H.L._Hunley",
		"Toire no Hanako-san (folclore)",
		"Blue Star Acid",
		"Consonno",
		"Scimmia Skunk",
		"Cimitero delle Fontanelle",
		"The Company of Undertakers",
		"Teletrasporto",
		"Villa dei Misteri",
		"Santa Nonna",
		"Razzismo scientifico",
        "Lingua romanza d'Africa",
		"Labirinto di Meride",
		"Ammasso della Chioma",
		"Olivetti Elea 9003",
		"Religione Jedi nei censimenti",
		"Le due Babilonie",
		"Escopetarra",
		"Pantalica",
		"Treno turbogetto",
		"Sei gradi di separazione",
		"Arco (lampada)",
		"Lettera del Diavolo",
		"Tabi",
		"Minuto di 61 secondi",
            "Kunsthaus Tacheles",
            "The Brig",
            " Lorem ipsum",
            "Casu frazigu",
            "Batracomiomachia",
            "Ora del Garda",
            "Frislanda",
            "Pacific Trash Vortex",
            "Giraffa dei Medici",
            "Thomas Midgley",

            "Alert",
            "Coober Pedy",
            "Cosmic latte",
            "Metropolitan Life Insurance Company Tower",
            "Battaglione \"Azad Hindoustan\"",
            "Giuseppe Castiglione",
            "Bouncing bomb",
            "Teorema della scimmia instancabile",
            "Berta filava",
            "Love Canal",

            "Il poeta mangiatore di leoni nel covo di pietra‎",
            "Caccia parassita",
            "Santi di ghiaccio",
            "Kormoran (HSK 8)",
            "Motivi geometrici islamici",
            "Franz Reichelt",
            "Séraphine de Senlis",
            "La nona onda",
            "Raggio verde",

            "Organo del Boardwalk Hall Auditorium",
            "King Camp Gillette",
            "CG 36500",
            "Fulmine globulare",
            "Leelah Alcorn",
            "Bottiglia Codd",
            "Silbo gomero",
            "Mummia di Manchester",
            "Monte Stella (Milano)",
            "Synsepalum dulcificum",
            "Frank Lentini",
            "Sindrome_di_Stendhal",
            "Bomber stream",
            "Macchine anatomiche",
            "Ambasciatori (Holbein il Giovane)",
            "Incidente di Gleiwitz",
            "Operazione Chrome Dome",
            "Ab anbar",
            "Coseano",
            "Clavier à lumières",
            "Torre Guinigi",
            "Guerra meteorologica (1940-1945)",
            "Elephant walk",
            "Jim Abbott",
            "Dingo Fence",
            "Fiat Mefistofele",
            "D.B. Cooper",

            "sindrome della mano aliena",
            "Rappresentativa Calcistica Dipendenti Vaticani",
            "Battaglia dell'Isola Ramree",
            "Isola delle Rose (micronazione)",
            "Kitty Genovese",
            "Volto su Marte",
            "Tumore facciale del diavolo",
            "Pykrete",
            "The Elements",
            "Deflategate",
            "Alfabeto Deseret",

            "Strada del Karakorum",
            "Tarzan Boy",
            "Suolo poligonale",
            "Digit ratio",
            "Moresnet",
            "Perito (astronomia)",
            "Hákarl",
            "Autoscatto del macaco",
            "Elvavrålet",

            "Repubblica di Cospaia",
            "Aeroporto di Barra",
            "Alan Smithee",
            "Ambasciata Tenshō",
            "Sinodo del cadavere",
            "Centralia (Pennsylvania)",
            "Citrus bizzarria",
            "Calitri",
            "Disco di Festo",

            "588º Reggimento bombardamento notturno",
            "Uomo di Tollund",
            "Moretto fiumano",
            "Balaeniceps rex",
            "Isabella di Morra",
            "Signora di Brassempouy",
            "Psiconautica",
            "Horsetail Fall",
            "Avvelenamento di massa di Pont-Saint-Esprit",
            "Casa sulle nuvole",
            "Dreamachine",
            "Otaku",
            "Beffa della Dreadnought",
            "War_of_the_Worlds_(programma_radiofonico)",
            "Effetto Dunning-Kruger",

            "Seawise Giant",
            "Box junction",
            "Vallone dei Mulini",
            "Muretto di Alassio",
            "B. Traven",
            "Settembre eterno",
            "Galleria dell'Eufrate",

            "Panthera leo persica",
            "Tyrrell P34",
            "Pando (albero)",
            "Alaska Railroad",
            "Cunicoli di Claudio",
            "Inter-Services and Dominions Rugby Championship",
            "Bestia del Gévaudan",
            "Off the Wall (album Michael Jackson)",

            "80 cm K (E)",
            "Victor Lustig",
            "Linciaggio di Jesse Washington",
            "Yanar Dag",
            "Dickin Medal",
            "Giorno del pi greco",
            "Filatoio Rosso di Caraglio",

            "Maddalena Ventura con il marito e il figlio",
            "Bosio & Caratsch",
            "Fortezza di San Nicolò",
            "Seebad Prora",
            "Khnumhotep e Niankhkhnum",

            "Casa della Storia europea",
            "Colle dell'Iseran",
            "Ponte sullo stretto di Bering",
            "Incidente ferroviario della stazione di Parigi Montparnasse",
            "Diari di Hitler",
            "Nannie Doss",
            "XXV della campagna romana",
            "Isola di North Sentinel",
            "Nigella sativa",
            "Vasa (galeone)",
            "Kopi Luwak",
            "João Lourenço",

            "Teleferica Massaua-Asmara",
            "Problema di Monty Hall",
            "Marco Izzo",
            "Pyramiden",
            "Concessione italiana di Tientsin",
            "problema di Monty Hall",
            "Città murata di Kowloon",
            "Sark",
            "Francesco Foglia",
            "Carlo Airoldi",

            "YInMn Blue",
            "Vegetarianismo di Adolf Hitler",
            "Battaglia di Los Angeles",
            "Silene stenophylla",
            "Cacareco",
            "Italica (nave)",
            "Pianoforte_a_gatti",
            "Eduard Bloch",
            "Campo profughi di Latina",

            "Paradosso dell'area scomparsa",
            "Sonata per clavicembalo K. 30",
            "Disastro di Balvano"
    ));

	public static String getRandomItem() {
		Collections.shuffle(wikipediaItems);
		return WIKI_PREFIX + wikipediaItems.get(0).replaceAll(" ","_");
	}

	public static String getRandomNonciclopedia(ArrayList<String> listItems, ArrayAdapter<String> adapter) {
		String item = null;

		try{
			RetrieveNonciclopediaTask task = new RetrieveNonciclopediaTask(listItems, adapter);
			task.execute();
		}catch (Exception e){
			e.printStackTrace();
		}

		return  item;
	}

	public static void main(String[] args){
        System.out.println("Size: " + WikiConstants.wikipediaItems.size());
        System.out.println("Duplicates: " + getDuplicate(WikiConstants.wikipediaItems));
        System.out.println(generateLinks(WikiConstants.wikipediaItems));
	}

    private static String generateLinks(ArrayList<String> wikipediaItems) {
        String output = "";
        for (String el : wikipediaItems) {
            output += "[[" + el + "]]\n";
        }
        return output;
    }

    public static <T> List getDuplicate(Collection<T> list) {

        final List<T> duplicatedObjects = new ArrayList<T>();
        Set<T> set = new HashSet<T>() {
            @Override
            public boolean add(T e) {
                if (contains(e)) {
                    duplicatedObjects.add(e);
                }
                return super.add(e);
            }
        };
        for (T t : list) {
            set.add(t);
        }
        return duplicatedObjects;
    }
};